### PR TITLE
Remove junit vintage engine, no more JUnit 3/4

### PR DESCRIPTION
**Pull request by easbar**
After replacing `@Theory` (#2310) and class-wide parameters (#2312) moving from JUnit 4 to 5 entirely is 'only' a matter of changing the import statements and assertion method calls and I did this here.

### CODE REVIEW

**Comment by karussell** [comment]
Oh, wow. Really nice - didn't notice this :) :+1:

**Comment by AnLogLabster** [comment]
I saw the earlier thread but just hadn't had time to refresh my memory on JUnit in order to mount a meaningful response, but it seems like you've got it all covered 👍

**Comment by Anvoker** [comment]
I saw the earlier thread but just hadn't had time to refresh my memory on JUnit in order to mount a meaningful response, but it seems like you've got it all covered 👍

**Comment by easbar** [comment]
Thanks a lot four your initial work on this @Anvoker! Can I add you to the contributors list?

**Comment by Anvoker** [comment]
If you think that's enough to warrant it, then sure thing! Don't see why not.

**Comment by easbar** [comment]
I just saw you are already on the list :) But anyway I updated it here: d141dbde06c3d1d813c71d3204258b5b7a3fca15

**Pull request merged**
