### PR TITLE
Add support for tag "smoothness", implements #655.

### PR DESCRIPTION
**Pull request by ratrun**
After a long time an implementation for #655.

### CODE REVIEW

**Comment by karussell** [comment]
Thanks! Do you have examples where this PR leads to an improved routing?

**Comment by ratrun** [comment]
Sorry, I do not have any real-world example. I tried to find one via overpass, but this is not that easy as most of the bad smoothness values are located within forest area.

**Comment by karussell** [comment]
Without a real-world example it is not really possible to review the effect of it. Should we implement such a change at all if there is no such situation in real world?

**Comment by ratrun** [comment]
I found a real world example: https://graphhopper.com/maps/?point=47.874663%2C16.120527&point=47.888809%2C16.110849&locale=de&vehicle=bike&weighting=fastest&elevation=true&turn_costs=false&use_miles=false&layer=Omniscale 
The two segments with bad surface are rather short (https://www.openstreetmap.org/way/543917919 and https://www.openstreetmap.org/way/805552627), but should be enough to take the route along the primary road with the modifications.
Even if it is hard to find real world examples where other ways are taken the modification improves the estimation of the travel time as lower speed values are assumed when the surface gets bad.

**Comment by karussell** [comment]
Oh, it seems this tag occurs quite frequently: over 2 million times on ways.

Instead of creating the mechanism inside the FlagEncoder I would create a new `smoothness` encoded value that can be used in a custom model (and in the FlagEncoder). Would you have time to rewrite this? If yes, let me know if you need help with this.

**Comment by ratrun** [comment]
I have managed to implement the encoded value for `smoothness` (see https://github.com/graphhopper/graphhopper/compare/master...ratrun:smoothnessEV). Shall I create a separate pull request for this? Unfortunatelly I have no idea how the new stuff could be used in the bike flag encoder and what you mean by that.

**Comment by karussell** [comment]
> I have managed to implement the encoded value for smoothness (see master...ratrun:smoothnessEV). Shall I create a separate pull request for this? 

Thanks for this and yes a pull request is appreciated. We can then use the smootness EncodedValue in the FlagEncoder for the default bike vehicle. 

> Unfortunatelly I have no idea how the new stuff could be used in the bike flag encoder and what you mean by that.

Usually we would use the EncodedValue in a custom model. See e.g. the examples or custom-model.md documentation. But it is also possible to integrate it in the older FlagEncoder architecture. See e.g. 

> roundaboutEnc = getBooleanEncodedValue(Roundabout.KEY);

in AbstractFlagEncoder. And a similar thing could be done with the smoothness to access the value (which is filled before from the TagParser)

**Comment by ratrun** [comment]
I have created the pull request for the enocded value, see #2303 as suggested. I also tried to use the encoded value in the BikeCommonFlagEncoder, but without success. I ran into "IllegalArgumentException: Cannot find EncodedValue smoothness in collection: null." when I tried to execute the enhanced tests. 
In the meantime I found a similar location in the car flag encoder: `applyBadSurfaceSpeed` is also acccessing the surface tag of the way directly like the code in this pull request above does.  There is no usage of the encoded value for surface, too. I would ask you to rewrite that car part first such that I can better understand what you mean. I'm sure that I'll manage to rewrite the BikeCommonFlagEncoder for usage of the smoothness encoded value with such an example.

**Comment by karussell** [comment]
> I ran into "IllegalArgumentException: Cannot find EncodedValue smoothness in collection: null." when I tried to execute the enhanced tests.

Ah, I think we would need to automatically add the parser whenever a BikeFlagEncoder is added: https://github.com/graphhopper/graphhopper/blob/master/core/src/main/java/com/graphhopper/routing/util/EncodingManager.java#L336

**Comment by ratrun** [comment]
Closing discussion here, we contine in #2303.

**Pull request closed without merging**
