### PR TITLE
Allow exporting alternative routes

### PR DESCRIPTION
**Pull request by boldtrn**
As discussed in #649, exporting alternative_routes is not possible yet. Therefore, I added a parameter to allow exporting a single path of the alternative routes.

WDYT?

### CODE REVIEW

**Comment by karussell** [comment]
Sorry, that I answer a bit too late ... saw your comment in #649 ... I would prefer to return multiple alternatives in one GPX to save resources as with this approach multiple requests are necessary for multiple alternatives. And to keep the API stable return multiple results **only** if alternatives are requested.

**Comment by devemux86** [comment]
Aren't we talking about an extra option to select the exported path?
Current behavior doesn't change, it's all about provide better API to the user.

**Comment by karussell** [comment]
> Current behavior doesn't change, it's all about provide better API to the user.

Alternatives are currently not allowed for gpx export, so this is an API change and the usage is suboptimal in the explained ways which we could avoid IMO

**Comment by boldtrn** [comment]
> Alternatives are currently not allowed for gpx export, so this is an API change

Yes, that is true, but it does not break any existing behavior.

> the usage is suboptimal 

Actually, I don't think so. There are scenarios where only a single exported path is preferred to multiple exported paths. See for example my comment in #649.

I still think that when trying to export an `alternative_route` without a `path_index` all paths should be exported. But this is something we can implement in the future?

**Comment by karussell** [comment]
The problem is that this export requires an up front request with the JSON response to determine the number of alternatives and so it is stateful and every follow up request issues an expensive alternative route search (or did I misunderstand this?)

**Comment by karussell** [comment]
In this state I would not merge it. There must be something better, like a gpx export with all alternatives. I know many clients would not support this but the client side could pick the required alternative (now in GPX format), ie. there would be just one underlying routing request.

**Comment by boldtrn** [comment]
>  it is stateful and every follow up request issues an expensive alternative route search

This is correct yes.

> There must be something better, like a gpx export with all alternatives

The problem is that when importing the track (or route) most navis don't understand importing alternative routes, so it would not make sense to do this. Maybe we could create n gpx files and zip them, but this is also not a good solution...

> but the client side could pick the required alternative

But this requires xml parsing and writing logic on the client side, which I personally would like to avoid.

**Comment by karussell** [comment]
> But this requires xml parsing and writing logic on the client side, which I personally would like to avoid.

Yes, sure. Both is bad. Another option could be to return multiple GPX strings within a JSON ;)

**Comment by boldtrn** [comment]
> Another option could be to return multiple GPX strings within a JSON ;)

Not sure if I want to do this either ;).

Let's leave it closed for now, maybe we find a better solution in the future.

**Pull request closed without merging**
