### PR TITLE
Incorporate filter search into the finding of the closest node search.

### PR DESCRIPTION
**Pull request by crowmagnumb**
The problem is as I discussed about the filtering. It's not a question of does the expanded search find a node or not, it's does the expanded search find a node that passes my filter. Inside of findClosest the findNetworkEntries returns a set of node ids, then we loop through these nodes using the edge explorer and the supplied filter. The basic search does not find a node that passes my filter so findClosest returns a "null" QueryResult. If I try and expand the search further I still don't find my node because no matter what value of maxRegionSearch, findNetworkEntries returns the first set of nodes that it finds but I already know those don't pass my filter, so once again they don't pass my filter and I get a "null" result. 

I've added the boolean to allow the filtering of the edges to be built into the search mechanism. I only added it to maintain backwards compatibility. I honestly don't see why this is not just done automatically.

### CODE REVIEW

**Comment by karussell** [comment]
Hmmh, I don't understand your usecase. Can you give me an example of how you use this? E.g. You want to find the closest bus station or something?

Also we need tests for this feature otherwise your use case will be lost or broken when a new refactoring comes in.

Furthermore I would prefer to avoid exploring within findNetworkEntries as this method is just about collecting nodes. So we need some kind of a loop over 'collect & explore & filter the edges' where the filter can also decide if the search should be stopped or not.

**Comment by karussell** [comment]
Hmmh, you are holding more vehicles and location index returns earlier with only 'car edges'?

**Comment by KenSoutherland** [comment]
Well, that is a pretty good example you just gave, and in a sense I am
doing something similar. I have a bunch of utility poles that I have to
visit. For each one I find the edge it is on and thus make a list of all
the edges I need to visit. Then starting with the first I route the user to
that edge, after that I route them to an adjacent edge if there is one in
the list. If not, I then use the findClosest() to find the closest edge
that is in my list of edges that I have to visit and then route them there,
and so on until I have visited all my edges.

**Comment by KenSoutherland** [comment]
I'm not sure what you meant by that.

**Comment by karussell** [comment]
So what you want is the best tour for N points? And what you currently do is a heuristic solution to that problem, it is not optimial, right?

**Comment by KenSoutherland** [comment]
It is absolutely not optimal because N can be as large as say 1000. i.e. very large. It is not possible in our lifetimes to find the optimal solution. What I find is a damn fine route that is pretty darn good. Optimal? No.

**Comment by KenSoutherland** [comment]
And incorporating the explore in the find results in a much more efficient algorithm. If this is not the desired behavior for all cases (again, I really can't see why not, at least from the stand-point of the findClosest() routine) then I propose a separate routine for this.

**Comment by karussell** [comment]
That heuristic should be good, yes.

Still the LocationIndex is the wrong tool for what you want IMO. What you could do is to use Dijkstra with many destinations:

```java
QueryGraph qGraph = new QueryGraph(graph);
qGraph.lookup(yourLocations);
Dijkstra dijkstra = new Dijkstra(qGraph, encoder, weighting, TraversalMode.NODE_BASED) {
   @Override protected boolean finished() {
        // your condition e.g. a set of (virtual) nodes
    }            
};
// TODO currently not public
dijkstra.runAlgo();
```

Or just calculate ALL distances between ALL locations and feed an optimization tool (for <10 you can do brute force search). Calculating all distances or times is easy with our [Matrix API](https://github.com/graphhopper/directions-api/blob/master/README.md#matrix-api) but with plain GraphHopper and two simple for-loops that is often also acceptable fast.

**Comment by karussell** [comment]
The problem with the LocationIndex and your usecase is that there is no order guaranteed, where Dijkstra guarantees that it visits the closer edges first.

**Comment by karussell** [comment]
Still there might be indeed a problem if e.g. your graph contains car and bike streets, now you search for the closest bike street but the findNetworkEntries method returns only nodes exploring car streets (e.g. close to a motorway)

**Comment by KenSoutherland** [comment]
It is not the routing problem I need solved. I have my routing problem and it's solved. What I wrote above was a great oversimplification of the problem, giving you just enough info necessary for this discussion. To say that using Dijkstra to solve my problem is missing the mark.

But you keep getting glimpses of my problem. Your example of bike vs. car streets is exactly the same issue as I am having. If you use my version, that problem goes away.  :)

**Comment by karussell** [comment]
I've fixed this issue - see my new pull request: #488

Slightly more refactoring was necessary. It also should be faster on average now.

@crowmagnumb if my new change is not working as expected in your case, please let me know!

**Comment by crowmagnumb** [comment]
Thanks! Sorry I haven't had time to check as I've sinced changed jobs and have not been working on this for a while. If I get back to that, and some day I hope to, I will definitely check it out.  Cheers.

**Pull request closed without merging**
