### PR TITLE
Fix for issue 546

### LINKED ISSUE #546: Should bicycle=yes be really stated as cycleway?
I got an email stating that [this path](https://graphhopper.com/maps/?point=45.350622%2C11.671686&point=45.351723%2C11.666236&locale=en&vehicle=bike&weighting=fastest&elevation=true&layer=OpenStreetMap) is not a cycleway it is only highway=track|path and bicycle=yes

### PR DESCRIPTION
**Pull request by ratrun**
Improve bicycle waytype classification for a bicycle=  tag on roads.

The intend is to fix #546

### CODE REVIEW

**Comment by ratrun** [comment]
I have no idea why travis is failing with JDK8, I don't think that it is related to the changes. 

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.18.1:test (default-test) on project graphhopper: Unable to generate classpath: org.apache.maven.artifact.resolver.ArtifactResolutionException: Unable to get dependency information for org.apache.maven.surefire:surefire-junit4:jar:2.18.1: Failed to retrieve POM for org.apache.maven.surefire:surefire-junit4:jar:2.18.1: Could not transfer artifact org.apache.maven.surefire:surefire-junit4:pom:2.18.1 from/to central (https://repo.maven.apache.org/maven2): Connection reset

**Comment by ratrun** [comment]
Very strange. The tarvis failure disappeared.

**Comment by karussell** [comment]
Sorry, I just restarted it without a comment here.

**Comment by karussell** [comment]
Thanks, [merged](https://github.com/graphhopper/graphhopper/commit/c12d2514b112684447922ff38b04be352a6a2c4f) after clarification in #546

**Pull request closed without merging**
