### PR TITLE
Initial implementation of GTFS support

### PR DESCRIPTION
**Pull request by initdch**
It is a simple implementation to support public transport and GTFS import. I tested it with Dijkstra and real world data and it works very well.

The `GTFSReader` uses GraphStorage to generate a time-expanded graph from a gtfs file. The time is encoded in the graph structure. Therefore, for each station multiple nodes are created which represents the station at a given time. The distance between nodes are the time difference in seconds. 

For GTFS import the onebusaway-gtfs library is used. But trips which uses frequencies.txt are not yet supported.

 `GHPublicTransit` is modeled after `GraphHopper` and  can be used as high level interface. 
 There is also `PublicTransitMiniUI` which can be used to test and debug GTFS files.

### CODE REVIEW

**Comment by dtamm** [comment]
Any intentions on reloading this pull request? I am very interested in working with this kind of code (maybe even contribute to it).

**Comment by karussell** [comment]
We rely here entirely on the community and this PR is very old. But we highly appreciate all contributions.

**Comment by dtamm** [comment]
Then i will try myself with implementing the old files (which were coded for graphhopper-0.1.1) for the latest version of graphhopper and test it with some GTFS Data i got.

**Comment by karussell** [comment]
Thanks! If you need help, just ask on the mailing list

**Comment by dtamm** [comment]
Thanks, will do! Already tried myself on implementing the files this morning for graphhopper-0.4.1 and got some errors (due to missing classes)... will list them all and ask for help on the mailing list (after some tries of myself).

**Pull request closed without merging**
