### PR TITLE
Specify trackname in UI fixes #559

### LINKED ISSUE #559: GPX: track name as user input included in metadata
GPX export generates metadata with useless track name.
Example: <name>OpenLayers_Feature_Vector_4023</name>
Most of the Garmin outdoor devices (e.g. Oregon series) are using the trackname in the metadata of the GPX file to identify the track (<name>trackname</name>). With "OpenLayers_Feature_Vector_xyz" the tracks can't be distinguished on the device so the GPX-files must be edited manually before using on such devices.

The GUI for GPX export could be enhanced with an input text field where the user can determine the final name of the track which will be stored in the GPX file. This helps users which are not familiar with GPX-editing to distinguish multiple GPX-files in there Garmin devices.

### PR DESCRIPTION
**Pull request by sskkcisos**
Mostly UI changes and parameter passing to include specifying trackname. So did not add any test cases

Fixes #559

### CODE REVIEW

**Comment by karussell** [comment]
Thanks - looks good to me! Just a tiny change: would you add a backward compatibility getParam call to still include the old `trackname`? E.g. tn = getParam("gpx.trackname", ""); if (tn.isEmpty) getParam("trackname", "GraphHopper Track") or something similar?

**Comment by karussell** [comment]
Also send me your email regarding [our CLA](https://github.com/graphhopper/graphhopper/blob/master/.github/CONTRIBUTING.md#license-agreement) and feel free to add yourself [here](https://github.com/graphhopper/graphhopper/blob/master/CONTRIBUTORS.md)

**Comment by sskkcisos** [comment]
I will send the CLA by Monday

**Comment by sskkcisos** [comment]
Review comments done

**Comment by karussell** [comment]
Would you mind to send the CLA?

**Comment by sskkcisos** [comment]
Hi,

       Sorry for the delay. Its pending approval from my organisation so
its taking some time. Will send it in a day or two

Thanks,
Saravana

**Comment by karussell** [comment]
You could also send me a personal CLA if this wasn't done at or for your company

**Comment by karussell** [comment]
@sskkcisos let me know what the status is here I would not like to reject this :)

**Pull request closed without merging**
