### PR TITLE
Add Motorroad RoadClass

### PR DESCRIPTION
**Pull request by otbutz**
Uses the same logic as the CarFlagEncoder to determine if a highway should be treated as a motorroad and uses a dedicated RoadClass constant to encode it.

### CODE REVIEW

**Comment by karussell** [comment]
We'll likely not include this as motorroad is just a `trunk` with different access values. We had this discussion in the initial PR: https://github.com/graphhopper/graphhopper/pull/1548#issuecomment-499165188

**Comment by boldtrn** [comment]
How about we add motorroad as its own boolean encoded value? There are some primaries which are motorroads and internationally there are a lot of trunks that are no motorroad. That way everyone who needs this value can set it up individually.

This also makes sense when looking at OSM. In OSM motorrad is a different tag than highway and I think we should not mix the two :).

**Comment by karussell** [comment]
I see no real benefit of this tag from the routing perspective if we can use `trunk` and some additional access restrictions. If this cannot be (easily) replicated we can think of including it via a boolean, sure.

**Comment by otbutz** [comment]
At least the CarFlagEncoder seems to use it to enforce a different default speed.

**Comment by boldtrn** [comment]
I don't know if we need it for routing, but I could think of examples where this can be relevant. If you think about flexible routing. Some vehicles for example are not allowed on motorroads, but are allowed on trunk roads, that are no motorroad.

Here is an example:
https://www.openstreetmap.org/way/202170525#map=17/43.47096/-5.14263
https://goo.gl/maps/ij1t2yi2Zzf8x8X99

In OSM, this is a trunk. This is also tagged correctly. But if look at it on Google Streetview, it is quite clear that it's not what I would consider a trunk.

**Pull request closed without merging**
