### PR TITLE
Added Roundabout Instruction

### PR DESCRIPTION
**Pull request by jansoe**
This introduces extra instructions for roundabouts (i.e. enter roundabout and take exit 3). This is achieved by subclassing Instruction as RoundaboutInstruction. 
Furthermore every instruction now contains its angle (radian).

Things still to improve:
* Better description by splitting insturctions for entering and leaving roundabout (in translation document)
* Improve angle calculation by considering slip roads (relates to #94)
* Expose full roundabout information to json

Code change has no measurable influence on calculation time of instructions (0.3ms of 3ms for Duesseldorfarea )

### CODE REVIEW

**Comment by karussell** [comment]
Thanks! Also for the bunch of tests!

I'll try it tomorrow. Some notes:

 * we need to expose the roundabout information to JSON similar to instructions. As we add the angle to the roundabout instructions we should probably also do for all other.
 * Additionally we have to think how to expose the `clockwise` variable, either we use a separate property OR we use additional constants like `Instruction.USE_ROUNDABOUT_CW`,  `Instruction.USE_ROUNDABOUT_CCW`, `Instruction.USE_ROUNDABOUT_INVALID`? I tend to prefer the first, but would like to discuss.
 * the other points you mentioned are okay if done later
 * to avoid casting to RoundaboutInstruction you can assign it to a temporary variable: `RoundaboutInstruction tmpInstruction = new RoundaboutInstruction` and as a last step do `prevInstruction = tmpInstruction` -> read: casting is often ugly and sometimes even a sign of bad design (but yes, sometimes not possible in a different way).
 * Place the open bracket on a new line (maybe we can create an IntelliJ profile similar to what I have in NetBeans). This is none-standard Java coding style but the way we do it currently in GH
 * As the radian is a field in the Instruction class you can expose it directly there: `Instruction.getRadian`

Also as you have asked to be nit-picky ;)
 * To get the encoder you can grab it more directly, no need for string based stuff: `private final FlagEncoder encoder = new CarFlagEncoder(); private final EncodingManager manager = new EncodingManager(encoder);`
 * make the tests a little more separate - e.g. one method for clockwise roundabout and one for counterclockwise
 * instead `public boolean getContinuedStreet()` the getter for boolean is in Java: `isContinuedStreet()`
 * I would use only positives as variable instead of `unfinished` I would use `finished` as `!unfinished` is too complex for me ;)
 * The inline comment should come *before* somethings happens e.g. instead of 
`int someVar; // some comment` do it in two lines:
```
// some comment
int someVar;
```

Only sometimes I use one line and behind e.g. as you did sometimes to describe the if-else clauses.

**Comment by devemux86** [comment]
:thumbsup:

**Comment by jansoe** [comment]
thanx for the comments.
eventually I also missed some test failure, i will fix it tomorrow, and i adress your comments:
* i agree we should include the angle for all instructions in the json
* by this we could easily code for the clockwise variable: positve radian -> counterclockwise, negative -> clockwise, and if undetermined getRadian throws an error or special value >2pi 
* Unfortunately I can't assign the Roundabout Instruction to a temporary variable because, the instructions "lives" for consecutives iterator calls.
*  getRadian is already there :) and just overwritten in the RoundaboutInstruction class  

So far, more tommorow

**Comment by karussell** [comment]
> eventually I also missed some test failure

Yeah, in RoutingAlgorithmIT there are some tests failing. Maybe some distance addition or points are missing?

> and if undetermined getRadian throws an error or special value >2pi 

undetermined can only be for tagging problems or strange roundabouts we do not know yet, right? I would prefer `Double.NaN`

> Unfortunately I can't assign the Roundabout Instruction to a temporary variable

Yeah, I just meant within the one if to avoid casting in the loop (I can also change afterwards and you see what I meant or maybe even leave it as it is)

> getRadian() is already there :)

ups, perfect :) !

**Comment by jansoe** [comment]
> Yeah, in RoutingAlgorithmIT there are some tests failing. Maybe some distance addition or points are missing?

Are there still some test faiures? For me everything worked fine after fixing a bug when starting in Roundabout.

**Comment by karussell** [comment]
Ah, missed the commit you did yesterday. Looks fine now. Do you want to add json stuff here (or should I?) and merge later or separate issue?

**Comment by jansoe** [comment]
I would adress your comments right now, including json and then push here.
If you prefer to implement the json interface by yourself go ahead.

**Comment by karussell** [comment]
Nice and yes, if you would do the json stuff it would be even better :)

**Pull request merged**
