### PR TITLE
Alternate route2

### PR DESCRIPTION
**Pull request by boldtrn**
This is a first idea of how to refactor the calcPaths method. The tests are still failing because I changed the behavior using Exceptions at some point. But I guess this can be fixed with little effort.

### CODE REVIEW

**Comment by karussell** [comment]
What is the reasoning behind this refactoring?

The exception handling should not change as I would like to be able to indicate multiple problems with the request e.g. if one or more location cannot be found.

**Comment by karussell** [comment]
Ups, I see that you mention the reasoning in another comment :)

> @karussell Would you mind if we refactor the calcPaths method in terms of length? Break it down into smaller methods. The method is now approximately 200 lines long. It becomes really hard to focus on the essentials of that function.

**Comment by boldtrn** [comment]
I will revert the exception handling. I ran out of time but wanted to show the approach and discuss, if we want to proceed with this. Instead of using a method. The inner class approach seems to be a good idea to me.

**Comment by karussell** [comment]
I'll have a look into it. In general I do not like large methods but I also do not like premature optimization - i.e. if there is no problem then there is no problem ;)

**Comment by boldtrn** [comment]
Maybe I was over-engineering, but in my opinion the calcPaths method is too long. It is easy to get lost and it's really hard to get the essentials of that functions. It should be split up into several smaller methods in my opinion.

**Comment by karussell** [comment]
I see you argument and although 150 lines is kind of 'big' it is also acceptable at the moment.

Mainly the method is a 3 step process and does the job of feeding the low level API: 
 * do location lookups (QueryResult), create QueryGraph and Weighting
 * calculate single paths
 * merge paths if necessary

Instead of artifically trying to separate methods I would propose a different refactoring where we try to split:

 * setup (Config)
 * import, CH preparation (Writing) and
 * loading, querying (Reading) 

into own classes/methods and if still necessary tie them together via the GraphHopper class. And we should do this after #450 is completed.

**Comment by boldtrn** [comment]
Ok let's close this PR.

> 
* do location lookups (QueryResult), create QueryGraph and Weighting
* calculate single paths
* merge paths if necessary

In my opinion we should separate the calcPath method into these three methods in the future.

Splitting the GraphHopper.java class into 3 separate Classes that are wrapped by the GraphHopper.java class is actually another refactoring, that is really important. A class should have one purpose.

**Comment by karussell** [comment]
> In my opinion we should separate the calcPath method into these three methods in the future.

Okay. Then this refactoring can be done also on its own (be it before the split or after)

> A class should have one purpose.

Yes, definitely. And one has to define what 'one purpose' is, so a bit subjective. Until now it was 'make some routes' ;)

**Pull request closed without merging**
