### PR TITLE
Don't interpolate travel times in GPX; fixes #1490

### LINKED ISSUE #1490: Time stamps calculated by  `createGPXList()` are sometimes inaccurate
The time stamps of a GPXList obtained from `createGPXList()` are sometimes inconsistent with the results of another GraphHopper call. The duration of a route from the origin to the the point of the entry in the GPXList can differ from the time stamp of the entry by several seconds.

This happens even when all requests are using the "fastest" weighting. See [here for a failing test of createGPXList()](https://discuss.graphhopper.com/t/time-stamps-in-gpxlist-inaccurate/3629/12).

This issue occurs with Graphhopper versions 0.10.3, 0.11.0, and the master branch as of the time of this writing.

### PR DESCRIPTION
**Pull request by michaz**
(See issue #1490.) The reason those timestamps are inaccurate is that they are made up. The code that generates the GPX thinks that every track point must have a timestamp, so it just makes up the timestamps for points where none is available (pillar nodes, I guess).

But that's not true, timestamps are optional. Just don't include them when we don't have one.

We _could_ get accurate travel times out of the routing engine, but that's not what the code wants to do -- structurally, it says that a GPX track is another representation of an instruction list, and the instruction list doesn't know travel times at pillar nodes.

This was all pretty hidden and non-obvious, because the code was mixing up the data model with its serialization: `InstructionList` looked like it could legitimately be converted into a `List<GPXEntry>` with mandatory timestamps, when in fact it couldn't.

So I went completely down the rabbit hole and mostly untangled it. The GPX generation is now with the other serializers, and all the tests that were for some reason testing against JSON instead of the data classes now don't.

### CODE REVIEW

**Comment by michaz** [comment]
Note that this still doesn't do what the OP of #1490 wants (travel times at pillar nodes). It just makes it clear that the stuff about `GPXEntry` is for creating GPX-XML and nothing more -- it doesn't contain any information that `InstructionList` doesn't contain already.

**Comment by karussell** [comment]
This is much cleaner. Finally you moved this xml out of the core and we have it like with the JSON (now crying for more serializers ;)).

@devemux86 do people use GPX in Android? And would this still work using jackson serializer? Or is this the same problem like in #1550?

**Comment by devemux86** [comment]
> @devemux86 do people use GPX in Android?

Very much or you mean just the GPX export in GraphHopper core?

> And would this still work using jackson serializer? Or is this the same problem like in #1550?

The pull request fortunately does not introduce new dependencies in GraphHopper core or you mean something else?

**Comment by karussell** [comment]
>  The pull request fortunately does not introduce new dependencies in GraphHopper core

It moves instructionList.createGPXList and createJson to the InstructionListSerializer

**Comment by devemux86** [comment]
> It moves instructionList.createGPXList and createJson to the InstructionListSerializer

In Android most need to import ready GPX files, not create them from routers, so don't know how much use actually had those methods. Anyway they don't need extra dependencies, just create a plain text file so it's easily doable.

**Comment by karussell** [comment]
Thanks for the clarification!

**Pull request merged**
