### PR TITLE
Refactoring of GraphHopperStorage to fix #111

### LINKED ISSUE #111: More efficient graph storage via separating shortcuts from edges
Separating shortcuts from edges could have some advantages:

 * This would reduce storage size. Because some fields are not necessary for shortcuts and some not for edges: no edgeIds in normal edges, no dynamic array for shortcuts necessary, no wayGeometry pointer for shortcuts, ...
 * related to #339
 * it would be possible to support multiple vehicles for CH -> multiple prepare calls

To do this we would need to think about some points:

 * probably we should store shortcuts different than edges as they do not need to be appended later on. E.g. just one block of edges per node
 * Having multiple profiles in one graph for the world wide case is extreme, so e.g. in the near future the edgeId limit of 2 billion is reached a lot quicker than with one profile per graph. Not if we have multiple, separate shortcut lists (every shortcut list forms a separate LevelGraph with the normal edges)

### PR DESCRIPTION
**Pull request by karussell**
This pull request is a major rewrite of some core parts of GraphHopper (storage and access of CHGraph, old name LevelGraph). This fixes #111. E.g. GraphHopperStorage now contains graphs like base graph and a ch graph which will allow for the physical separation of edges and shortcuts. 

Currently there are the following steps before we can merge this:
- [x] merge master into this
- [x] rename LevelGraph* to CHGraph*
- [x] separate node_ch_refs for CHGraphImpl to avoid base graph going through shortcuts
- [x] test with none CH algo on prepared graph should pass now
- [x] make base graph see only its edges (no shortcuts). edge count for level graph and base graph should change (e.g. getAllEdges.count)
- [x] all tests should pass now
- [x] fix all TODOs in the source code, and can we add edges count to locationindextree.calcChecksum? And can we avoid requiring the GraphHopperStorage and use a Graph instead in DijkstraBidirectionCHTest.createFactory
- [x] fix some bugs uncovered while refactoring, but do this in different issues
- [x] separate shortcut DataAccess in CHGraphImpl

Later we can also have multiple ch graphs but for that we should create a new issue besides #339

Some bugs uncovered while refactoring:
 - [x] setNodesHeader returns wrong used header size
 - [x] internalEdgeDisconnect -> use N_EDGE_REF for nodes.setInt
 - [x]  bug if next is called after setAdditionalField? if (extStorage.isRequireEdgeField()) iter.setAdditionalField(extStorage.getDefaultEdgeFieldValue());
 - [x] bug in test testFindShortcuts_Roundabout regarding skipped edges of shortcut 6,4
 - [x] bug in alledgeiterator detach => reverse can be incorrectly set if detach(false) and reverse=true, can only happen if detach is called on an already detached iterator which would involve a cast
 - [x] bug in alledgeiterator found: while iteration edgepointer can get bigger than valid edges and if it would be compacted then even array index out of bounds would get thrown
 - [x] if too many names are stored => wrong check for long value instead int! (check AllEdgesIterator and EdgeIterable)
 - [x] here it should be getNodes instead of getCapacity! removedNodes = new GHBitSetImpl((int) (nodes.getCapacity() / 4));
 - [x] shouldn't we throw an exception in CHGraphImpl instead of returning? public final void setLevel( int nodeIndex, int level ) { if (nodeIndex >= baseGraph.getNodes()) return;

(where marked they are fixed in the pull request but not master yet)

### CODE REVIEW

**Comment by devemux86** [comment]
Thanks Peter for providing also a summary of API changes in changelog, it helps studying the code changes.

**Comment by karussell** [comment]
If you find something you do not understand, please let me know!

Also this is now different and needs to be changed:
> call GraphHopperStorage.getBaseGraph(). To do routing with potentially shortcuts you call GraphHopperStorage.getGraph(encoder)

to "GraphHopperStorage implements now the Graph interface and delegates all necessary methods to the underlying base graph. To do routing you call getGraph(LevelGraph.class or Graph.class) where the parameter Graph.class currently returns the base graph and the behaviour is identical to GraphHopperStorage itself" (this is the convenient change I mentioned in the other issue)

**Comment by karussell** [comment]
The additional refactoring for #339 will be done in a separate step. Now finalizing before like improving readability and performance checks. 

Also to all: as all tests pass please review.

While refactoring I found some bugs
 - [x] (fixed in branch+master) bug in test testFindShortcuts_Roundabout regarding skipped edges of shortcut 6,4
 - [ ] bug in alledgeiterator detach => reverse can be incorrectly set if detach(false) and reverse=true
 - [x] bug in alledgeiterator found: while iteration edgepointer can get bigger than valid edges and if it would be compacted then even array index out of bounds would get thrown
 - [ ] here it should be getNodes instead of getCapacity! removedNodes = new GHBitSetImpl((int) (nodes.getCapacity() / 4));

(where marked they are fixed in the pull request, only the first is also fixed in master too)

An open question is: move the BaseGraph implementation back into GraphHopperStorage to make everything simpler?

**Comment by devemux86** [comment]
>An open question is: move the BaseGraph implementation back into GraphHopperStorage to make everything simpler?

And what about ```chGraph```?

**Comment by karussell** [comment]
> And what about CHGraph?

CHGraph will stay separate. But moving BaseGraph back would have the advantage of avoiding the method delegation in GraphHopperStorage to the BaseGraph. Although I like the separation of storage and traversal stuff... but CHGraph currently also mixes storage and traversal :)

**Comment by devemux86** [comment]
Ok you're probably right here.

**Comment by karussell** [comment]
You mean moving it back into GraphHopperStorage? Just asking again as I'm still unsure ... probably I'll let if for now as it is until we find a reason pro or contra?

**Comment by devemux86** [comment]
>You mean moving it back into GraphHopperStorage?

Yes. I'm a bit sceptical about ```GraphHopperStorage``` hosting [both](https://github.com/graphhopper/graphhopper/blob/issue_111/core/src/main/java/com/graphhopper/storage/GraphHopperStorage.java#L42-L44) types of graphs.
With the change it will be Base itself and still contain the CH?

**Comment by karussell** [comment]
> I'm a bit sceptical about GraphHopperStorage hosting both types of graphs.

What do you mean? Or what do you think could improve the situation? Keep in mind that we'll need in the near future multiple chGraphs managed by the GraphHopperStorage. But via ghstorage.getGraph(class) it should be very simple to extend for more purposes or even other algorithms.

> With the change it will be Base itself and still contain the CH?

Yes, this would be a bit uglier design-wise but simpler.

**Comment by devemux86** [comment]
I'm fine with current PR implementation.

>With the change it will be Base itself and still contain the CH?
>Yes, this would be a bit uglier design-wise but simpler.

Here I had second design thoughts but as you said it'll be simpler, so it's ok.

**Comment by devemux86** [comment]
Well I suppose (depending on ram) it could work.
Sorry not having something usable in mind right now.

**Comment by karussell** [comment]
Some numbers for the area 'Germany': 15% less storage and therefor RAM - as expected :) !
Routing same speed. But strangly CH routing is 20% slower, also preparation is 18% slower. To be investigated

**Comment by devemux86** [comment]
:+1: 
What algorithm, bidirectional Dijkstra ?

**Comment by karussell** [comment]
Yes, to better compare CH and none-CH I've picked bidir dijkstra in both cases -> See the measurement class (or graphhopper.sh measurement area.pbf)

**Comment by karussell** [comment]
Although I only slightly improved the speed situation I'll merge this request soon as there are many advantages.

disadvantages, higly likely due to the additional EdgeAccess layer:
 * 12% slower CH preparation
 * 12% slower CH routing

advantages:
 * 10% less storage/RAM used
 * 5% faster routing, but highly likely via an unrelated change https://github.com/graphhopper/graphhopper/commit/3b197460a3a9aabb1dd5e8f47e47ef58bf49e668
 * separated edges from shortcuts storage, as well as CH entries (`nodesCH`) from normal traversal entries (`nodes`), allowing us to add multiple CH profiles in the near future
 * making other speed-up techniques easier pluggable in the future
 * better architecture via composition (EdgeAccess, CHGraphImpl and BaseGraph) instead of extension (`LevelGraphStorage extends GraphHopperStorage`)

**Comment by devemux86** [comment]
I follow your code changes so :+1: for that.

**Comment by karussell** [comment]
@devemux86 thanks for the feedback!

BTW: It would be now also possible to revert the speed we lost with #338 but we would need to introduce two integers for additional `ch refs` in the normal `edges` DataAccess storage, and the levels per node could be removed. Leading to a slight RAM increase of ~0.5GB = (2-1)*0.5GB for the world wide case. Then we could entirely avoid the LevelEdgeFilter for normal edges too, giving us a rough boost of 15-20%

BTW2: The levels should not be removed (although no longer needed right now). Instead we should just avoid to load them into RAM. Because when edge weights change and we need to recreate the CH profile the levels could then be reused and the CH preparation could be a lot faster then - at least from what I know from papers.

**Comment by devemux86** [comment]
Peter I started playing with latest GH code.
I see with this PR old graphs do not work, right?

**Comment by karussell** [comment]
Yes, because there is now a separate shortcuts and edges storage. Any problems I didn't think about with this :) ?

**Comment by devemux86** [comment]
I try all the cases (e.g. loading a CH graph with a non CH config) and I see the same error message, let me conclude my tests and come back.

**Comment by devemux86** [comment]
Yes I think something is not right (or I'm doing wrong!).

I have created a CH graph and I'm able to load it with ```graphHopper.setCHEnable``` either ```true``` or ```false```.

**Comment by karussell** [comment]
That is like it should be :)

You can now run without performance lost normal routing algorithms even if CH is enabled, which means you can also load the graph without the ch datastructure and everything should work - at least in theory ;)

**Comment by devemux86** [comment]
Oh I missed that step.
I support all possible GH cases in graph loading (via exception catch) - so it was strange to me.
It seems now that I can loosen the checks, thanks for the tip.

**Comment by devemux86** [comment]
Since now we cannot be notified if a graph has CH or not, we need to always use ```graphHopper.setCHEnable``` at reader in order to be sure that we actually use the CH in CH graphs.
Since this ```set``` works with non CH graphs also, that would be not a problem.
On the contrary the false ```set``` means that we may loose CH in those graphs.
Is this thought correct?

**Comment by karussell** [comment]
Ah, okay. I see what you mean. 

> Because the setCHEnable(true) works also with non CH graphs

That is a problem which we should indeed fix! Either we automatically detect CH and configure everything accordingly like we do partially for the flagEncoders, or we should throw an exception. Feel free to create an issue!

> On the contrary, the setCHEnable(false) means that we may loose CH in those graphs.

That is not such a big problem IMO as the results should be still correct, but yes this should be fixed probably at the same time.

**Pull request merged**
