### PR TITLE
Added lane information based on the osm tag turn:lanes

### PR DESCRIPTION
**Pull request by aramzl**
lane_info=true in the encoder string to enable it, it requrires 8
bytes_for_flags.

@karussell 
@boldtrn

Issue #1131

### CODE REVIEW

**Comment by boldtrn** [comment]
Thank you very much for your contribution and sorry for the late reply. This PR looks very impressive. Having turn lane support would be great.

Since turn lanes are not important for the routing itself and are only required for the TurnInstruction generation, I would probably put them in a DataAccess, similar to the NameIndex. As you have seen yourself, it requires a lot of bits, and bits are very precious :). Using a DataAccess we could even think about just storing the whole turn:lane information and not needing to encode it (I am not sure if we cover every possible turn lane combination?).

WDYT @karussell, could we merge something like this, using DataAccess before #1112 or do we have to wait until #1112 is finished?

Regarding the PR itself, you included the tag `turn:lanes`, but not `turn:lanes:forward` and `turn:lanes:backward`. I think this will make the code a bit more complicated, but a lot of turn lanes are tagged like this, so I think it would be required to have that information.

**Comment by aramzl** [comment]
@boldtrn Thanks for the comments. I saw the turn:lanes:forward and turn:lanes:backward I wanted to make a second pull request including them. It will take more memory (more bits are needed).

**Comment by boldtrn** [comment]
> @boldtrn Thanks for the comments. I saw the turn:lanes:forward and turn:lanes:backward I wanted to make a second pull request including them. It will take more memory (more bits are needed).

There is a way to get around this by using a DataAccess, similar to the NameIndex or TurnCostExtension. Let's wait for Feedback from @karussell before deciding our next steps :).

**Comment by karussell** [comment]
Thanks @aramzl for this useful and big feature!

I'm not sure if we should merge such a complex thing before #1112 as this will highly likely needs a bigger refactoring. If you would have time it would be really interesting to see if you could base your PR on the mentioned branch. This could be also used as a test case if everything what we need is already possible

**Comment by karussell** [comment]
Thanks @aramzl for this useful and big feature!

I'm not sure if we should merge such a complex thing before #1112 as this will highly likely needs a bigger refactoring. If you would have time it would be really interesting to see if you could base your PR on the mentioned branch. This could be also used as a test case if everything what we need is already possible

**Comment by aramzl** [comment]
I would try to redo it based on #1112 and create another pull request.

**Comment by karussell** [comment]
This is awesome! Please note that this is cutting edge, and could potentially use lots of your time ... we really appreciate your feedback e.g. if this feels better from a programming perspective.

**Comment by karussell** [comment]
Will close here, then resurrect #1269 (include the tests from here, maybe wait until #1548 is merged)

Sorry that this takes so long @aramzl. Now that #1447 was merged this is a much better time to do your change. Have marked #1269 for 0.13

**Pull request closed without merging**
