### PR TITLE
move resolving of custom areas and profiles in graphhopper#init()

### PR DESCRIPTION
**Pull request by lukasalexanderweber**
For me it seemed like a bug that my custom profiles were not added correctly when initializing graphhopper from a config object. 

I then found [this forum answer](https://discuss.graphhopper.com/t/how-to-fix-error-custom-weighting-requires-a-customprofile-but-was-profile/6973/8) and wondered, if it would be possible to integrate the resolving into the core package (where I think it does belong). The tests pass (even when deleting `GraphHopperManaged#resolveCustomAreas` and `GraphHopperManaged#resolveCustomModelFiles` completely).

### CODE REVIEW

**Review by donPain — COMMENTED** [review]
Did the test performed before the change use a standard config.yml?

**Comment by lukasalexanderweber** [comment]
Hello @donPain, I just run `mvn clean test` within the Graphhopper parent directory. I havn't seen you around in earlier PRs, can you briefly outline your role within the Graphhopper preject?

**Comment by easbar** [comment]
Thanks, I moved the static methods that we use to resolve the custom model files and areas into core and they are now executed within GraphHopper#init: https://github.com/graphhopper/graphhopper/commit/0d7cc4e8f7cc02e1c9af4d09a6ddb689d8332d4e

**Comment by lukasalexanderweber** [comment]
Thanks!

**Pull request closed without merging**
