### PR TITLE
Improve avoidance of ways with high maxspeed values for cars

### PR DESCRIPTION
**Pull request by ratrun**
This change was triggered by a discussion on the mailing list , see https://lists.openstreetmap.org/pipermail/graphhopper/2015-May/001964.html .

Improve avoidance of ways with high maxspeed values for cars and control the avoidance with one car speed on AVOID_IF_POSSIBLE level and another speed limit for the REACH_DEST avoidance.

The AVOID_IF_POSSIBLE max car speed is now defined as 71 km/h for all bike types except for the racingbike.
The REACH_DEST max car speed is now defined as 81 km/h for all bike types except for the racingbike.
The AVOID_IF_POSSIBLE max car speed is defined as 81 km/h for the racingbike.
The REACH_DEST max car speed is defined as 101 km/h for the racingbike.

### CODE REVIEW

**Comment by karussell** [comment]
Hmmh, I would like to avoid the complexity of having two speed limits for this. Where did you encounter a real world problem with the current status and is the change improving the situation?

**Comment by ratrun** [comment]
This change was triggered by this an answer mail on the mailing list for this example

https://www.openstreetmap.org/directions?engine=graphhopper_bicycle&route=64.13323%2C-21.86841%3B64.13484%2C-21.87089#map=17/64.13394/-21.86962

in this mail: https://lists.openstreetmap.org/pipermail/graphhopper/2015-May/001964.html .

The user titled a `higway secondary maxspeed=50` as a "multi-lane fast traffic" road. During writing the answer I came to the conclusion that the current code with the check for >80km/h is not good because there are many roads with a speed limit of exactly 80.

The extension with the two limits is just logical in order to better serve the racing-bike use case. Most racing-bike people are able to cope with faster traffic. But there is also a limit for them. So I introduced the second limit.

**Comment by karussell** [comment]
At least for this example I think it will be fixed once your change regarding bicycle=yes is deployed. Also traffic light recognition would help and I do not like this speed check that much. E.g. what if a high speed is allowed but the street is not crowded or if only 50 km/h and very full street. As we know these issues of the speed check I would like to avoid relying even more on them and making the code complexer.

**Comment by ratrun** [comment]
You are right. The changes in #412 will probably solve the mentioned example. But I think that this change would improve the situation for other cases, where smaller roads run nearby faster roads. Would you accept the change if I reduce the complexity and use just a single maxspeed value?

**Comment by karussell** [comment]
Yes, please just use one speed like before and maybe set different values for the different bikes (race vs. normal)?

**Comment by ratrun** [comment]
Thanks for the improvement comment. Now it is indeed cleaner. Could you please check once more?

**Comment by karussell** [comment]
Looks good, thanks!

**Pull request merged**
