### PR TITLE
Improved responsiveness of Web UI #2005

### PR DESCRIPTION
**Pull request by jguddas**
This PR fixes the following issues:

**the line graph being cut of on small screens**  
solved by adding dynamic width adjustment

before:  
image

after:
:warning: I was unable to test this with europe_germany_berlin.pbf :warning:

**the route information disappearing on small screens**  
solved by adding a min height of 100px

before:  
image

after:  
image

**missing support for small screens**  
solved by tweaking the css in a media query

before:  
image

after:  
image

### CODE REVIEW

**Comment by easbar** [comment]
> I was unable to test this with europe_germany_berlin.pbf 

I just tried this and the elevation widget seems to be invisible. All we see are the open/close buttons:

image

image

**Comment by jguddas** [comment]
@easbar I think I fixed the issue.

I'm still unable to test it after changing the config and doing a clean rebuild, thanks for your help anyway.

**Comment by karussell** [comment]
Unfortunately I have the same problem as @easbar.

> I'm still unable to test it after changing the config and doing a clean rebuild

Can you describe the problem why you are unable to test this?

What I did to test this: I switched to your branch. Then I downloaded the berlin-latest.osm.pbf, used the sample config and enabled elevation like  @easbar described. Then removed the `graph-cache` folder. Then `cd web-bundle` and `npm run watch` and finally started GH with IntelliJ to force a fresh import. Or instead you can also build the jar via command line `mvn clean install` and run as described in [the readme](https://github.com/graphhopper/graphhopper/#installation).

**Comment by easbar** [comment]
> Unfortunately I have the same problem as @easbar.

After the latest commits the elevation widget was visible for me. But it did not adjust its width. Another problem was that after using the full screen button some parts of the screen remained white, so the space was not used.

**Comment by easbar** [comment]
Thanks for your work and also your latest fix. The full screen issue seems to be resolved. I cannot really say much about the css code, but just by testing the results I think this PR is an improvement compared to master. I tested for both Chrome and Firefox.

**Comment by easbar** [comment]
Ah but now I got another error (in the browser's console):

```
map.js:285 Uncaught ReferenceError: infinity is not defined
    at Object.module.exports.addElevation (map.js:285)
    at HTMLLIElement.<anonymous> (main-template.js:659)
    at HTMLLIElement.dispatch (jquery.js:5429)
    at HTMLLIElement.elemData.handle (jquery.js:5233)
    at Object.trigger (jquery.js:8715)
    at HTMLLIElement.<anonymous> (jquery.js:8793)
    at Function.each (jquery.js:381)
    at jQuery.fn.init.each (jquery.js:203)
    at jQuery.fn.init.trigger (jquery.js:8792)
    at jQuery.fn.init.jQuery.fn.<computed> [as click] (jquery.js:10738)
```

It depends on the screen size, but this `infinity` variable in `map.js` seems to be non-existing.

**Pull request closed without merging**
