### PR TITLE
create routing template in a factory function for easy override

### LINKED ISSUE #1713: Make it possible to use a custom SnapPrevention
The snap prevention feature is great. I just wanted to modify the snap prevention in a project that uses GraphHopper as a library. Unfortunately, it's not possible to override the snap prevention easily. It would be nice to have an easy way to do this.

One thing that could already help would be to move the RoutingTemplate creation in the GraphHopper class into an overridable method:
```
// Move this part into a method
            RoutingTemplate routingTemplate;
            if (ROUND_TRIP.equalsIgnoreCase(algoStr))
                routingTemplate = new RoundTripRoutingTemplate(request, ghRsp, locationIndex, encodingManager, maxRoundTripRetries);
            else if (ALT_ROUTE.equalsIgnoreCase(algoStr))
                routingTemplate = new AlternativeRoutingTemplate(request, ghRsp, locationIndex, encodingManager);
            else
                routingTemplate = new ViaRoutingTemplate(request, ghRsp, locationIndex, encodingManager);
```

Then we could allow passing different EdgeFilters in the constructor of the RoutingTemplate or make the ViaRoutingTemplate extendable to use different EdgeFilters.

WDYT?

### PR DESCRIPTION
**Pull request by naser13**
Fixes #1713.

### CODE REVIEW

**Comment by easbar** [comment]
The concept of routing templates is likely to be removed soon. Can you explain what kind of use case you have in mind? See also this related issue: https://github.com/graphhopper/graphhopper/issues/1869

**Comment by naser13** [comment]
thank you @easbar 
but the issue #1869 will not satisfy my use case.
i have this situation: i have started a new project and added graphhopper as a dependency, per requirements i need to change lookup behaviour of the routing template. currently there is no clean way of doing that from outside graphhopper, but if routing templates had a factory i could have written my own routing template and use it.
also same thing for pathMerger behaviour

**Comment by easbar** [comment]
Ok I understand. The thing is that in the future `GraphHopper` shall no longer be extensible by overriding some parts of it. It should rather be a convenience type of thing to cover some standard features (or maybe it will be split into smaller classes altogether). More advanced use-cases (like the custom lookup behavior you mentioned (you mean the location index lookup bwt?)) should be doable by just combining some library components in different ways. Unfortunately at the moment this is not so easy to do, because for example `GraphHopper#calcPaths` does way too many things that cannot be reused so easily. Afaik we can merge this change for now, but please do not consider this to be stable of any sort. If you explain in more detail what custom behavior you are trying to achieve it might help with some future design decisions, and maybe its even something that would be useful for the upstream project.

**Comment by naser13** [comment]
thanks again for your answer.
i understand that changes are on the way that will make this pr obsolete and change the way things are done. but for now it would be appreciated if this gets merged so i can continue further developments.
and yes by lookup i meant location index lookup; i wanted to consider bearing when finding closest edge and filter by edges that have similar bearing so for example if i am at a junction it doesn't match me with the wrong edge.
as for the bigger changes you mentioned, is there a thread about them somewhere?

**Comment by easbar** [comment]
>  it would be appreciated if this gets merged so i can continue further developments.
Can you send your license agreement (see contribution guidelines)?

>  i wanted to consider bearing when finding closest edge and filter by edges that have similar bearing so for example if i am at a junction it doesn't match me with the wrong edge.

Feel free to open a separate issue for this and maybe your changes can be used for master.

> as for the bigger changes you mentioned, is there a thread about them somewhere?

See this issue: #1895

**Comment by naser13** [comment]
> Can you please send your license agreement (see contribution guidelines)?

done

> See this issue: #1895

looks promising. graphhopper is improving very fast.

**Comment by boldtrn** [comment]
I have faced a similar issue in the past, #1713

**Comment by easbar** [comment]
Thanks!

**Comment by easbar** [comment]
Ugh for some reason the commits werent squashed and not attributed to you. If you want we can try again (add add a revert commit and apply the same changes again)

**Pull request merged**
