### PR TITLE
Avoid Pattern compilation

### PR DESCRIPTION
**Pull request by otbutz**
The old code would need to compile two Pattern instance for each call of `simpleXMLEscape()` as `String.replaceAll()` requires that a Pattern is compiled on each call. The PR switches one of the replaceAll() calls to a simple replace() as it doesn't require regex functionality. The other one is compiled once and gets reused.

### CODE REVIEW

**Comment by karussell** [comment]
Did you have a problem in production due to this?

> The PR switches one of the replaceAll() calls to a simple replace() as it doesn't require regex functionality. 

:+1:

**Comment by otbutz** [comment]
Just Sonarlint screaming on top of its lungs :smile:

**Comment by otbutz** [comment]
Any objections?

**Comment by easbar** [comment]
Thanks

**Pull request merged**
