### PR TITLE
Further documentation of the Core docs

### PR DESCRIPTION
**Pull request by henningvs**
A few more comments about the linked docs in /docs/index.md

### CODE REVIEW

**Comment by karussell** [comment]
Thanks a lot! Can I ask you for a separation of the title (with the link) and a `:`? For example
> Set up and run GraphHopper in Eclipse**:** Detailed instructions how to ...

Or that every entry instead of "title:description" is a normal sentence with parts of it used for the link?

**Comment by henningvs** [comment]
Sure I will do this. I will use the first method you proposed as I think it will be more clearly for the reader.

**Comment by karussell** [comment]
Thanks :) !

**Comment by henningvs** [comment]
I'm really glad to help.

**Comment by henningvs** [comment]
Let me know if I should change something.

**Comment by karussell** [comment]
Thanks!

**Pull request merged**
