### PR TITLE
Skip ways with sidewalk=no.

### PR DESCRIPTION
**Pull request by Rungee**
for example http://www.openstreetmap.org/way/155062104 .

### CODE REVIEW

**Comment by karussell** [comment]
That is important, thanks! Still I would avoid complete blocking in these cases and instead just decrease the priority. Would you mind to have a look into the collect method and provide this as a PR?

**Comment by Rungee** [comment]
I assume that this tag was proposed for a simple reason. Walking along such a street can be very dangerous. But, if you insist on avoiding complete blocking, then I could try to move it into the collect method.
By the way, there is also a similar value "none" which is used much more often. Take a look at statistics
http://taginfo.openstreetmap.org/keys/sidewalk#values

**Comment by karussell** [comment]
Probably you are right regarding the meaning but even primary roads are allowed and sometimes necessary to pass if there would be otherwise no way or a big detour. If foot should be blocked there would be foot=no? I'm not a mapper so maybe we need some more community feedback regarding this.

Multiple values can be handled.

**Comment by karussell** [comment]
@ratrun do you have an opinion about this change?

**Comment by karussell** [comment]
@ratrun and @Rungee - can we close in favour of #476?

**Comment by ratrun** [comment]
I would close this here. Complete blocking is too restrictive, especially for devoloping countries.

**Comment by karussell** [comment]
But we have an open issue for the priority handling of sidewalks? (lost a bit the overview)

**Comment by karussell** [comment]
Closing due to #476 (and #463)

**Pull request closed without merging**
