### PR TITLE
make possible to run query after quickstart

### LINKED ISSUE #2350: Consider making simple example and quickstart compatible
**Describe the bug**
https://github.com/graphhopper/graphhopper/blob/0522c495ccad5f22fe19c6e858a40a7bd6f74eae/docs/web/api-doc.md#a-simple-example and https://github.com/graphhopper/graphhopper/blob/3.x/docs/core/quickstart-from-source.md are not compatible - it would be nice if simple example used locations in Berlin (if possible) so it would work for someone who followed quickstart

**To Reproduce**

1. follow quickstart
2. try to get road surface info ( https://discuss.graphhopper.com/t/possible-to-extract-street-types-and-average-speeds/6614/2 )
3. find https://github.com/graphhopper/graphhopper/blob/0522c495ccad5f22fe19c6e858a40a7bd6f74eae/docs/web/api-doc.md#a-simple-example
4. discover that I will need to fiddle with locations to get results

Instead of a manual reproduction it would be even better to have a unit or integration test reproducing the issue.

**Expected behavior**
Following quickstart and loading Berlin will enable me to run code examples using localhost (where possible, left side driving for example must be demonstrated elsewhere)

**System Information**

Provide version of Operating system, JVM and GraphHopper - is it REALLY necessary in this case?

**Screenshots & Logs**

not relevant

### PR DESCRIPTION
**Pull request by matkoniecz**
fixes #2350

> Please read [our contributing guide](https://github.com/graphhopper/graphhopper/blob/master/CONTRIBUTING.md) and note that also your contribution falls under the Apache License 2.0 as outlined there.

OK, though this one likely qualifies under "ineligible for copyright"

> Your first contribution should include a change where you add yourself to the CONTRIBUTORS.md file.
Also for such tiny ones?

### CODE REVIEW

**Comment by karussell** [comment]
This is a good idea - thanks a lot!

> Also for such tiny ones?

Sure, why not :) ...and who knows - maybe you continue contributing!

**Comment by matkoniecz** [comment]
> Sure, why not :) ...and who knows - maybe you continue contributing!

I prefer not right now, edit was done with in-browser github editor that is awful to use.

I will happily add myself in case I commit something in CLI.

**Comment by karussell** [comment]
> I prefer not right now, edit was done with in-browser github editor that is awful to use.

It is relative easy to append this change directly in the browser too: just go to the file in your repository and select your branch `patch-1`, then click the edit icon and after the change commit to the same branch `patch-1` instead of creating a new one. If you still don't want to be mentioned - this is fine too. Let me know.

**Comment by matkoniecz** [comment]
If extra commit is fine then I added myself :)

**Comment by karussell** [comment]
Sure (we squash those commits into a single one). Thanks!

**Pull request merged**
