### PR TITLE
Fixes some code formatting.

### PR DESCRIPTION
**Pull request by easbar**
I just updated an older branch to master and noticed that in the current master there are quite a few classes (63 actually) where default code formatting in IntelliJ changes existing code. 

image
Auto formatting breaks some javadocs, like this one in `InstructionsOutgoingEdges.java`:

image

Anyway, I fixed some (hopefully) harmless cases, because different formatting can be quite annoying as well ;)
The `reader-gtfs` module has a few more files that aren't formatted, but I wasn't sure if those should be adjusted as well, possibly risking unnecessary conflicts with other branches @michaz?

### CODE REVIEW

**Comment by michaz** [comment]
> The reader-gtfs module has a few more files that aren't formatted, but I wasn't sure if those should be adjusted as well, possibly risking unnecessary conflicts with other branches @michaz?

Yeah, I'd be happier if you wouldn't. Thanks. :)

**Comment by karussell** [comment]
Strange, why there are again so many formatting changes, see recently #1346. Maybe we should use some maven plugin that enforces this with every commit?

**Comment by ammagamma** [comment]
> Strange, why there are again so many formatting changes, see recently #1346. 

I think in #1346 we mostly fixed license headers and <> operator uses.

**Comment by karussell** [comment]
Having the code formatting consistent for all modules including reader-gtfs, would help also with refactorings that go across the whole project like issue 1447. What are the reasons we cannot apply the usual formatting here @michaz?

**Comment by michaz** [comment]
I don't mind any particular formatting, I just use long-running branches which are tedious to merge after global reformattings.

> would help also with refactorings that go across the whole project like issue 1447.

How?

**Comment by karussell** [comment]
> I just use long-running branches which are tedious to merge after global reformattings.

:+1: 

> > would help also with refactorings that go across the whole project like issue 1447.

> How?

When I edit a file I automatically do formatting as a lazy habit to avoid manual indenting which also leads to conflicts for longer running branches. But of course this is not important as I do this very rarely but just a note that we should migrate to a standard formatting in a year or so.

**Comment by karussell** [comment]
btw: in IntelliJ there is a "format on commit" option that we could use to migrate slowly (only a few edited files) to the same formatting for the whole project.

**Pull request closed without merging**
