### PR TITLE
Isochrone: Look for encroaching points that are not in the SPT

### PR DESCRIPTION
**Pull request by michaz**
Fixes issue #2181. Triangulates a couple more points. But, theoretically, we now don't need the slack in the SPT-size anymore, but can search just up to the asked z-value. So it'll be fewer points again.

### CODE REVIEW

**Comment by michaz** [comment]
Even though I think this is "technically correct", I'm not merging it for now, since it degrades performance quite a bit. At the same time, in situations _other_ than those in #2181, it sometimes gives _worse_ results. Reason is a combination of not having _constrained triangulations_ yet, and only taking the largest component of the possibly disconnected area, meaning that we chop off pieces of road that should be inside.

Tricky.

**Comment by michaz** [comment]
Okay, I removed the search-space slack -- now it's _not_ slower than master, but the disconnected area problem remains.

Try next:
- Add "exterior" nodes of isochrone edges (i.e. the first nodes that are _not_ inside the isochrone)
- _Don't_ add nodes from _inaccessible_ parts of the network (e.g. subnetworks, footpaths for car, etc.)
- _Then_ see if good enough
- Someday, get constrained triangulations

**Comment by michaz** [comment]
Not convincing yet.

**Comment by Rikuoja** [comment]
@michaz What is the main reason this pull request is closed? Does the branch work at least in principle, I have a use case in which I might need this behavior, even if I might need to verify the results manually? I.e. can you give an example of a disconnected area and chopping off pieces of isochrone?

**Pull request closed without merging**
