### PR TITLE
Update Isochrone documentation

### PR DESCRIPTION
**Pull request by NoamDev**
I realized it would be better to send a basic pr than create an issue.
I'm not an experienced documentor, so please review thoroughly.

### CODE REVIEW

**Comment by NoamDev** [comment]
Someone was faster than me:)

**Comment by easbar** [comment]
> Someone was faster than me:)

Oh sorry I did not know you are working on this as well, is there still something you would like to add? Thanks for your effort in any case.

**Comment by NoamDev** [comment]
Hmm, I think it should be noted that labels might update.
I mean, If the tree got to the same traversal id again, it'd send an updated label.
Maybe the example should insert all the labels to a map, so that updated labels would overwrite the old ones.

**Comment by NoamDev** [comment]
You can look on my commit for example.

To be honest, I think it should actually be a method.
It could be very confusing.

**Comment by easbar** [comment]
Ok sure sounds good feel free to update/re-open your PR.

**Comment by NoamDev** [comment]
Sorry, could you please say that again?
seems you wrote fast and I'm unable to understand it. Probably my fault as I;m not a native english speaker..

**Comment by easbar** [comment]
I had a look at `ShortestPathTree` again and I do not think that the labels are updated multiple times as `consumer.accept(label)` is called just after polling from the queue (just like I would have expected it to be). 

So I think:

>  If the tree got to the same traversal id again, it'd send an updated label.

does never happen. Do you have an example that shows labels that get called multiple times? Maybe you were using `TraversalMode.EDGE_BASED`? So currently I think there is no need to mention this in the docs and we do not need to build some `HashMap` for the example either.

**Comment by NoamDev** [comment]
You seem to be right!
I couldn't create a test case, and after some debugging, I realized it cannot happen.
Because it always pulls the lightest route, and a route which started heavy can never become lighter.
Routing algorithms are such an amazing thing!
Is that a _greedy_ algorithm?

**Pull request closed without merging**
