### PR TITLE
Android: advance to Mapsforge 0.5.1

### PR DESCRIPTION
**Pull request by devemux86**
Peter we published recently Mapsforge 0.5.1.

It would be good to integrate it to GraphHopper too.
I modified the Android sample where it was needed because of some API changes.

### CODE REVIEW

**Comment by devemux86** [comment]
By the way the mapsforge-map jar in Maven repository is back to normal.

**Comment by karussell** [comment]
Perfect & Thanks! This was just a bug fix release I guess?

**Comment by devemux86** [comment]
Actually we have added also some [features](https://groups.google.com/forum/#!topic/mapsforge-dev/CyE7_p_GIzQ) we had ready:
- SVG rendering for Java
- Multiple maps - ready for GraphHopper multiple graphs support :)
- Persistent cache
- I have added also an external Map Rotation example - suitable for navigation with GraphHopper until the native one is ready!

**Comment by karussell** [comment]
Thanks, nice!

**Pull request merged**
