### PR TITLE
prevent intellij build error "package sun.misc does not exist"

### PR DESCRIPTION
**Pull request by orangeman**

### CODE REVIEW

**Comment by easbar** [comment]
Thanks! I also had the same problem recently (using openjdk-11) and fixed it the same way.

**Comment by orangeman** [comment]
the issue only happens with intelliJ. openjdk-11 on the command line works fine

**Comment by easbar** [comment]
> the issue only happens with intelliJ. openjdk-11 on the command line works fine

yes same for me intellij (latest) using openjdk-11, no problems on the command line

**Comment by karussell** [comment]
Can we merge this or close here @easbar ?

**Comment by easbar** [comment]
I made this a bit more readable (hopefully). Yes this can be merged.

**Comment by easbar** [comment]
@orangeman Would you mind sending the license agreement so this can be merged? https://github.com/graphhopper/graphhopper/blob/master/CONTRIBUTING.md

**Comment by easbar** [comment]
@orangeman? Any interest in this otherwise I will close here

**Pull request closed without merging**
