### PR TITLE
Fix broken scalecontrol when switching between km to miles.

### PR DESCRIPTION
**Pull request by ratrun**
Switching between imperial and metric units got broken because of the leaflet update. This is fixed here.

### CODE REVIEW

**Comment by karussell** [comment]
What do you mean with broken scale control? I cannot see something broken here.

**Comment by ratrun** [comment]
Calculate a route such that distances are displayed in kilometers. When you now change the units, the left side buttom map scale GUI element still shows km, altough it should show miles. If you debug it in the browser you'll see something like ```scaleControl.remove``` is not a function.

**Comment by karussell** [comment]
I cannot reproduce this, did you refresh the browser cache?

**Comment by ratrun** [comment]
Strange. I initially detected the problem under nwjs, where it cannot be triggered from the browser cache as the page always gets completely loaded initally. Did you run `npm update` ? Eventually you did not and therefore you cannot reproduce it?

**Comment by karussell** [comment]
Yes. Do you see this on https://graphhopper.com/maps too? The latest version is already deployed there. Hmmh, strange. @fbonzon or @ammagamma can you reproduce this problem?

**Comment by fbonzon** [comment]
@ratrun You did not run `npm update`. The main.js file in your commit still reads "L.version = '0.7.7';"

**Comment by ratrun** [comment]
Thanks @fbonzon for pointing me on my still not updated leaflet version. I did run npm update, but probably in a wrong folder.

**Pull request closed without merging**
