### PR TITLE
Android Gradle advance, improvements

### PR DESCRIPTION
**Pull request by devemux86**

### CODE REVIEW

**Comment by karussell** [comment]
Thanks!

**Comment by devemux86** [comment]
I kept Android compile version to 22 (Lollipop) as we need first to see #498.

**Comment by devemux86** [comment]
BTW Peter why you have commented the ```jcenter```?
I know Google in recent AS builds puts only that and no ```maven``` at all.

**Comment by karussell** [comment]
> BTW Peter why you have commented the jcenter?

I do not know but all repositories should be identical, and I prefer to have consistency across compilation, but if it makes problems then include it again.

**Pull request merged**
