### PR TITLE
Android Sample: fix compile error, #451

### PR DESCRIPTION
**Pull request by devemux86**
Fix compile error in Android Sample due to #451 changes.

### CODE REVIEW

**Comment by karussell** [comment]
Uhm, sorry for the improper fix https://github.com/graphhopper/graphhopper/commit/8384dcfe8e268aba1b6a306299c8df0b72e6057d the problem is that my Android environment is not existent ;)

**Comment by karussell** [comment]
We should really fix #360 but never got the time for it ...

**Comment by devemux86** [comment]
No problem, happy to help.

BTW I think the graphs in the server need updating, right now they're incompatible with the master due to #281.

**Comment by karussell** [comment]
thanks, good hint as this does not happen automatically

**Comment by karussell** [comment]
0.5 graphs should be also up-to-date

**Pull request merged**
