### PR TITLE
String index

### PR DESCRIPTION
**Pull request by karussell**
This PR introduces a flexible storage to store key-value String pairs for every edge and will replace the NameIndex, so that we can store translated name tags ala name_ru, ref-tags separately or even arbitrary tags per edge. (It is basically a Map ala `Map<Long, Map<String, String>>` except that you cannot define Long when you put it and get it returned when you add the `Map<String, String>`.)

This PR only introduces the index, we still need a method like `edge.putExtra("key", "value")` and we could also introduce a generic StringPathDetails and replace StreetNameDetails. Related also to #1772.

The index has the following limitations:

 * append-only storage. I.e. updating existing key-value pairs for one edge is only possible via allocating more space
 * supports up to `32768-1` unique keys (max length of each is 65k) and holds them in-memory
 * arbitrary values with a length of 255 bytes (UTF-8). Is mostly sufficient, also for names.
 * it does a simple duplicate detection to reduce storage size, but does this only for identical keys or identical values or fully equal entry maps (no partial strings)

TODOs:

 - [x] the simpleCache brings 10% smaller size on disk but makes everything a bit more complicated
 - [x] store ints even if it needs to be split over 2 segments => use get+setBytes (or use padding?)
 - [x] is storing all tags already possible? Yes! How large does the index get => 221MB for Germany i.e. increases the total size by only 15% (5310 unique keys - make sure to exclude our artificial tags like estimated_center/distance and duration. Maybe also all tags that are already handled in our parsers)
 - [x] compare speed for bigger and smaller maps - looks good
 - [x] improve storage size further for larger maps like Germany. Trying to use [lz4-java](https://github.com/graphhopper/graphhopper/compare/getall_prototype...lz4_string_index) failed and even increased the size for the compressed data. But a very interesting tool is [zstd that can be trained](https://github.com/facebook/zstd/#the-case-for-small-data-compression) to specific data which would be likely beneficial for OSM data. A similar tool is http://ed-von-schleck.github.io/shoco/ but for now we'll keep every as it is.

### CODE REVIEW

**Comment by otbutz** [comment]
Looks good :+1: 

We could use this to store countrycodes per edge like i proposed it in #1709

**Comment by karussell** [comment]
Thanks! Works indeed surprisingly well.

> We could use this to store countrycodes per edge like i proposed it in #1709

In general this is more for the path extraction phase or for the MVT endpoint. It is not really suited for routing due to its design towards more compact size e.g. loops through all values of one edge. I'm sure for smaller areas it is still possible to do that, but this shouldn't be promoted in the core and should be done via EncodedValues instead.

**Comment by otbutz** [comment]
>In general this is more for the path extraction phase or for the MVT endpoint. 

That's exactly my use case as I would like to add country information to the path details. The StringIndex would allow me to do this fairly cheap and i could avoid adding ~250 countries to the `Country` enum  to get global coverage. Storing all this information in the graph would require roughly one byte per edge which seems like a waste of space considering that we currently ship just a few SpatialRule implementations.

**Comment by karussell** [comment]
> That's exactly my use case as I would like to add country information to the path details. 

Have a look into this branch: https://github.com/graphhopper/graphhopper/tree/getall_prototype

More a prototype (virtualedges won't work), but the rest seems to work fine and also for bigger areas:

image

You can even misuse this to store the OSM ID ... highly inefficient but oh well...

**Comment by michaz** [comment]
Thank you thank you thank you.

**Pull request merged**
