### PR TITLE
Collection.isEmpty() should be used to test for emptiness

### PR DESCRIPTION
**Pull request by kirill-vlasov**
This pull request is focused on resolving occurrences of Sonar rule squid:S1155 - Collection.isEmpty() should be used to test for emptiness
You can find more information about the issue here:
https://dev.eclipse.org/sonar/coding_rules#q=squid:S1155
Please let me know if you have any questions.
Kirill Vlasov

### CODE REVIEW

**Comment by karussell** [comment]
I remember we explicitly do not use String.isEmpty for Android compatibility somehow. @devemux86 can you confirm that these changes would be okay with Android? (E.g. if we want to support >2.3 ... or should we force 4.x?)

**Comment by devemux86** [comment]
Yes these changes are valid for the Android [minSdkVersion 10](https://github.com/graphhopper/graphhopper/blob/master/android/app/build.gradle#L9) we currently use in GraphHopper Sample.

Android [List.isEmpty](http://developer.android.com/reference/java/util/List.html#isEmpty%28%29) exists from the start and [String.isEmpty](http://developer.android.com/reference/java/lang/String.html#isEmpty%28%29) from API level 9 (aka 2.3).

>(E.g. if we want to support >2.3 ... or should we force 4.x?)

I wouldn't advance Android min SDK without very serious benefits / reasons.
i.e. in [Mapsforge](https://github.com/mapsforge/mapsforge/blob/master/build.gradle#L26) we continue supporting API 10.

**Comment by devemux86** [comment]
Forgot to mention that GraphHopper had to support API level 8 until the commit 10ef1bc7331e0f48975d9a00b1b4a54cfb63dadc this summer.

**Comment by karussell** [comment]
Thanks for this info! With 2.3 (level 9) this should be fine

**Comment by karussell** [comment]
@kirill-vlasov sorry, will need to fix the CLA stuff in the next 2 weeks and then we can merge your PRs

**Comment by karussell** [comment]
@kirill-vlasov we need your signature for the CLA. Didn't you receive the CLA request a few weeks ago? Otherwise we are forced to close all your good pull requests which would be a bit bad, see here for more information about the CLA: https://discuss.graphhopper.com/t/graphhopper-contribution-license-agreement/486

**Comment by karussell** [comment]
See my comment here: https://github.com/graphhopper/graphhopper/pull/629#issuecomment-204449727

**Pull request closed without merging**
