### PR TITLE
Use Policeman Tools

### PR DESCRIPTION
**Pull request by boldtrn**
This is a clone of #1213.

As mentioned in #1210, it would be nice to use the policeman tools to avoid locale issues.

I just pasted the default configuration of the policeman tools. I changed it so it does only run on travis or by using `mvn forbiddenapis:check`. It finds a lot of issues for the core so far.

### CODE REVIEW

**Comment by karussell** [comment]
Thanks!

Why is there a change to main.js?

**Comment by boldtrn** [comment]
> Why is there a change to main.js?

Because it changed in the master branch. When merging it will create a conflict. The easiest solution for me is to simply regenerate the main.js, that's why it detects a change. When squashing a commit, that has been updated from the master, this happens and I don't know how to get around this.

**Comment by karussell** [comment]
> Because it changed in the master branch. When merging it will create a conflict.

You should rebase it after that change so that this wouldn't happen. Or just exclude any changes of main.js from the commit and it should be easy to merge.

> When squashing a commit, that has been updated from the master,

What do you mean here?

**Comment by boldtrn** [comment]
> You should rebase it after that change so that this wouldn't happen. Or just exclude any changes of main.js from the commit and it should be easy to merge.

The issue is that if you want to update the changes from the master (fetch and merge), need to resolve conflicts and then squash, git does not understand that this was a merge conflict resolution. Or at least I don't know how to do it better, as I think there should be a way :).

**Pull request merged**
