### PR TITLE
add buildweb argument to graphhopper.sh which builds the graphhopper jar with the web module

### PR DESCRIPTION
**Pull request by edy**
I am using docker to run graphhopper. This pull request adds a new argument to the graphhopper.sh.
Now one can create (not only) docker images with a prebuilt graphhopper jar which also contains the web module.

### CODE REVIEW

**Comment by karussell** [comment]
Thanks!

**Comment by karussell** [comment]
Would you mind to send me an email? See our [contributing guide](https://github.com/graphhopper/graphhopper/blob/master/.github/CONTRIBUTING.md) regarding the CLA.

**Comment by karussell** [comment]
BTW: regarding docker: maybe you can help us there :) ? I know there are several docker files around in the web but I would prefer one which is maintained in the repo.

**Comment by edy** [comment]
well, i could write a Dockerfile for this project and send a you PR 😃

**Comment by karussell** [comment]
This would be really nice! Currently we put those 'misc' files a bit hidden in `core/files` like the postgis folder. But as a separate step we can/should move the required files&folders into a new `/files`

**Pull request merged**
