### PR TITLE
GPX: fix timestamp representation

### PR DESCRIPTION
**Pull request by devemux86**
Peter I think that in GPX the timestamps should be in UTC with ISO 8601 representation and end with the 'Z' suffix.
http://www.topografix.com/gpx_manual.asp#time

And to conform with spec, probably it's not necessary to provide the timezone as parameter to the createGPX method.

### CODE REVIEW

**Comment by karussell** [comment]
Thanks, this would be really a nice cleanup :) ! Did you try some of the common GPX programs if they are okay with this? (basecamp, some online tools, josm, osm.org?)

**Comment by devemux86** [comment]
Most readers (online, apps) are versatile enough to parse more than one timestamp patterns.
And I have found gpx files that don't follow the standard.

But going the other way, wherever I checked for official produced gpx files, I saw them following the spec.
(please inform us if someone has additional info)

**Comment by karussell** [comment]
When we use 'Z' shouldn't we force +0? I.e.:

```java
SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ssZ");
formatter.setTimeZone(TimeZone.getTimeZone("UTC"));
System.out.println(formatter.format(new Date()));
```
Otherwise I'll get incorrect time when using default time zone here in Germany.

**Comment by devemux86** [comment]
What do you mean, don't you get with the above code the UTC time ?

**Comment by karussell** [comment]
It will correctly use the local or specified time but ignores the offset as we always write 'Z'. I think you can easily try on your own. It should give you different times (except you are in london :)) but it will give you identical times

**Comment by devemux86** [comment]
Right not it gave me ```2015-03-23T21:15:00Z```

**Comment by devemux86** [comment]
That's the correct UTC time, what do you get?
(or I'm missing something here)

**Comment by karussell** [comment]
Strange, that you get it correctly. I get `2015-03-23T22:18:42Z` 
Also it makes sense to force UTC and avoid the default or a specific time zone when we always use +0

**Comment by devemux86** [comment]
The UTC timezone is needed or else as you said we'll get our current time.

I don't remember Java to have changes in that part (I'm in Linux with 7).

**Comment by karussell** [comment]
Okay, but then this old code is wrong with your change:

```java
TimeZone tz = TimeZone.getDefault();
if (!Helper.isEmpty(timeZoneId))
   tz = TimeZone.getTimeZone(timeZoneId);
```
and we should always use UTC and remove the timeZone parameter, right?

**Comment by devemux86** [comment]
Yes you are corrent, to be with the spec we shouldn't provide the user any timezone option, but use internally only UTC.

**Comment by devemux86** [comment]
Peter I pushed a new commit removing the timezone parameter and making the UTC default.

Also I think that in case of not provided ```startTimeMillis```, the current date should be used and not the 0.

**Comment by karussell** [comment]
Thanks & yes, you are right regarding the startTimeMillis

**Comment by devemux86** [comment]
I pushed another commit regarding ```startTimeMillis```.

**Comment by karussell** [comment]
Thanks!

**Pull request merged**
