### PR TITLE
GPX: introduce indentation in xml elements

### PR DESCRIPTION
**Pull request by devemux86**
Introduce indentation in GPX xml elements and move closing tags in new line.

That way we may read more easily the produced gpx and process it further.

### CODE REVIEW

**Comment by devemux86** [comment]
I fixed also the unit test.

**Comment by karussell** [comment]
Ok. Still opening an xml in a browser always formats you the xml, no?

**Comment by devemux86** [comment]
Well for just viewing it, but we may need to process it with an editor.
It would be convenient to be in a user readable format.

For the record OSRM gpx files are just one line, even harder to comprehend.

**Comment by karussell** [comment]
Sure, I understand. Are there any implications for other tools when including these new indentations (besides more kbytes)?

**Comment by karussell** [comment]
Hmmh, it looks like now several more chars per trackpoint are added, which indeed means several KB more data. I don't like this as it is just for the purpose of debugging we should introduce a debug=true parameter or avoid this completely as other tools (like the browser or xmllint) are there to do pretty print of xml

**Comment by devemux86** [comment]
It's your call but then we shouldn't have the current middle situation right now, where half the gpx file has some kind of indentation and the other is mixed up.

I suggest either to have it properly or have it compact (like OSRM).

**Comment by devemux86** [comment]
Peter I'm closing this PR as I need to reorganize my repository for other PR.

If there is still interest in the future, I can resend it.

**Comment by karussell** [comment]
Ok + I'm thinking now how we do this

BTW: If you do the PR suggestions on a branch you won't have this problem.

**Comment by devemux86** [comment]
>BTW: If you do the PR suggestions on a branch you won't have this problem.

Thanks, that's exactly what I neglected to do and want to reorganize.

**Pull request closed without merging**
