### PR TITLE
Add a force flag to download a file without any user input

### PR DESCRIPTION
**Pull request by legraina**
I have added a -f flag in the graphhopper.sh script to be able to run it correctly in a docker. The goal is to remove any input of the user, especially when trying to download a new file.
We can now run `./graphhopper.sh -f import europe_germany_berlin.pbf` without having:
```bash
File not found 'europe_germany_berlin.pbf'. Press ENTER to get it from: http://download.geofabrik.de/europe/germany/berlin-latest.osm.pbf
Press CTRL+C if you do not have enough disc space or you don't want to download several MB.
```

### CODE REVIEW

**Comment by karussell** [comment]
Thanks!

I regret a bit that we have such a limiting (but very simple) command line format and the force flag would be useful but does not really fit into the current schema. Also we plan to use dropwizard via #1108 that will require yet another slightly different parameter format, so I would postpone this for a bit.

**Comment by legraina** [comment]
Ok, so no need to try to fix the current script and be sure that all checks pass ? If you like to use something like that for the moment, I can make a version that is compatible with the previous versions and where you can add new flags. As you like.

**Comment by karussell** [comment]
Hmmh, I'm a bit undecided here as I've not looked yet very deep in the dropwizard change and I do not want to waste anyones time :)

My initial thought was to use the same parameter style for the script like we use for direct java call but this is probably not possible nor standard with bash parameter style.

**Comment by karussell** [comment]
The best would be something in the style of the java program like
```
./graphhopper.sh  --action web --datareader.file some.pbf
```

But maybe having this as a start with just `-f` is already good. Hmmh, but "force" could mean anything, maybe we should make the parameter more descriptive at the beginning and introduce short later on?

**Comment by legraina** [comment]
Yes, I can totally do that for the moment (it would be pretty easy). I would also keep the previous settings to remain backwards compatible.

**Comment by legraina** [comment]
I've added all these flags and also kept the positional arguments:
-h|--help
-f|--force-download
-a|--action
-d|--datareader.file
Does it seem good for you ?

**Comment by karussell** [comment]
Does not look too bad :) thanks!

>  -f|--force-download

can we do -fd here and for datareader.file the -f?

**Comment by karussell** [comment]
(Shouldn't sound negative regarding your work, sorry. Just still a bit hesitating to introduce yet another parameter format ...)

**Comment by karussell** [comment]
But maybe we can also iterate here after we merge the dropwizardifying

**Comment by legraina** [comment]
I've done the modifications. And no worry if you don't want :) I was doing these modifications to be able to use more easily the docker image (you can like that download and import any pbf file directly from the docker image, otherwise it's more tricky).

**Comment by karussell** [comment]
Thanks again! (Give me a few days over the holidays and I can better judge :))

**Comment by karussell** [comment]
I'm currently playing with [fish](https://fishshell.com/) and there is an interesting auto complete feature where the parameters and its description are shown. This would be cool to support - do you know if this is easy :) ?

**Comment by legraina** [comment]
From what I've seen, you cannot do that. To be able to have a nice completion in bash you need to load first the possible completion (https://debian-administration.org/article/317/An_introduction_to_bash_completion_part_2), and then you have access to an auto-completion. It means that you will have to 'install' graphhopper.

**Comment by karussell** [comment]
As we change the command line handling due to #1314 we have to rewrite the script a bit. The work you did here seems really useful and I'll try to see how we can use it to make a cleaner scripting possible.

**Comment by karussell** [comment]
Please have a look at #1319. Will close here for now.

**Pull request closed without merging**
