### PR TITLE
GraphHopperServerConfiguration auto-detects available ports

### PR DESCRIPTION
**Pull request by taulinger**
Removed fixation to port 8080. Each test class detects an available port itself now.

### CODE REVIEW

**Comment by karussell** [comment]
What is the use case here? Is it to have parallel tests?

**Comment by easbar** [comment]
I sometimes ran into this issue when something else on my system is running on port 8080 (this port is quite commonly used by all kinds of software)

**Comment by taulinger** [comment]
> I sometimes run into this issue when something else on my system is running on port 8080 (this port is quite commonly used by all kinds of software)

That's the point. In our case, we build GraphHopper on our internal CI-System, where port 8080 is also already in use.

**Comment by karussell** [comment]
Ok. Makes sense. Can we make creating this URL somehow easier? E.g. with a helper method?

```java
Builder clientRequest(App app, String path) {
   if(!path.startsWith("/")) path = "/" + path;
   return app.client().target("http://localhost:"+ app.getLocalPort() + path).request();
}
```

And instead of changing the production GraphHopperServerConfiguration can we do this only in the tests? E.g. extend it for a test config?

**Comment by karussell** [comment]
@taulinger thanks for the changes! Can you add yourself as a contributor (see CONTRIBUTORS.md) and [send us your Email address for the CLA](https://github.com/graphhopper/graphhopper/blob/master/CONTRIBUTING.md#license-agreement)?

**Comment by karussell** [comment]
Thanks!

**Pull request merged**
