### PR TITLE
Issue 310: Generated GPX file contains both <rte> and <trk> tags

### LINKED ISSUE #310: Generated GPX file contains both <rte> and <trk> tags
Hi, 

as discussed separately with Peter, I am encountering issues with the GPX graphhopper generates.
Indeed, as they contain both the rte and trk tags, the softwares I use are computing both thus generating a longer route than created.

As an example, I created the following mountain bike route: 
https://graphhopper.com/maps/?point=43.87287%2C7.006069&point=43.866868%2C7.005318&point=43.851581%2C6.99415&point=43.844123%2C7.026186&point=43.839665%2C7.087083&point=43.843999%2C6.993184&point=43.849879%2C6.967607&point=43.872792%2C7.006075&vehicle=foot&elevation=true&layer=TF%20Cycle

Here is a recap of the behavior I am getting with different tools:
 - josm display both the route and the track when opening the GPX file.
 - Oruxmaps on Android considers both rte and trk, thus a 35km track becomes a 60km route+track overall. The elevation profile is pretty clear: you see more than 20kms at elevation 0 and then the real track starts.
 - this website also has the same symptoms : http://www.visugpx.com/index.php?i=N4SHU8rKaV (the URL is valid for 24hours). Here is a screenshot (which is more or less what Oruxmaps does as well):

http://www.imagehangar.com/view.php?pic=small/29703700_1422363331.jpg

I'm not sure what should exactly be the content of the gpx and I understand both route and track have their use but it would be nice to have the choice when downloading the gpx.
For example, http://www.openrunner.com/ has 2 different buttons to generate the gpx: one for route and one for track.

Any thoughts about this?

Regards,
Florent.

### PR DESCRIPTION
**Pull request by ratrun**
Launch a popup window in JS where the user can select which GPX data parts shall be exported.
Additionally add the possibility for exporting of GPX waypoints.
Please note that it was necessary to update the jquery-ui version, as otherwise the popup diolog did not show up. I somewhere found the suggestion to update the version on stackoverflow and the updated version works.

Fixes #310

### CODE REVIEW

**Comment by karussell** [comment]
:+1: nice!

**Comment by karussell** [comment]
In the console it says to me: `$(...).sortable is not a function` and the web UI is scrambled a bit

Is the a js module missing?

**Comment by ratrun** [comment]
Yes, I'm sorry, one file was missing. Now its added and the change in update-translations.sh reverted.

**Comment by karussell** [comment]
Thanks! This is now merged, let me know if this is okay for you!

Note that I've changed the css IDs to avoid collision in the future and also the URL parameters have now a `gpx.` prefix. Furthermore additionally to `FIXME` in the source you should add it to the issue text. See the default change for 'route' via #437

**Comment by karussell** [comment]
deployed, need to document the new parameters

**Pull request closed without merging**
