### PR TITLE
Gradle: update Android build tools to 23.0.3

### PR DESCRIPTION
**Pull request by devemux86**
Update Android build tools to latest version.

### CODE REVIEW

**Comment by karussell** [comment]
Thanks! Does the maven config also need an update?

**Comment by devemux86** [comment]
No because in GH we build the Android sample only with Gradle.
Maven would require external [Maven Android SDK Deployer](https://github.com/simpligility/maven-android-sdk-deployer) procedures.

**Comment by devemux86** [comment]
If you want we can create an issue and I'll see what can be done.

Though it isn't something automatic, users would have to update manually their local repo first.

**Comment by karussell** [comment]
okay

BTW: I deploy the apk via maven and the sdk deployer via the pom.xml and it works (if one installs stuff before this ;))

**Pull request merged**
