### PR TITLE
Refactor prepare contraction hierarchies

### PR DESCRIPTION
**Pull request by thehereward**
Just a tiny amount of tidying.
I'm hoping to have a look through more of the code when I get time.
🎁

### CODE REVIEW

**Comment by karussell** [comment]
Thanks! 

Would you mind to squash the two commits into one :) ?

Also why do you need the creation separated? Would it make sense for you to change `private` to `protected`? Then one could modify the creation process via subclassing.

Furthermore I would call it createAStar... instead of getAStar...

**Comment by thehereward** [comment]
Thanks for such a quick reply!

> Would you mind to squash the two commits into one :) ?

Sure, will do :-)


> Also why do you need the creation separated?

It makes the code a bit easier to read: the `createAlgo` method is now much shorter and is just responsible for choosing which algorithm to create. The new methods are then responsible for actually creating the algorithm.


> Would it make sense for you to change private to protected? Then one could modify the creation process via subclassing.

This sounds more like a new feature than refactoring :-) I don't know enough about the code base to know if it is something we would want to make possible (and if it is there might be a better way of achieving it). If it is something we want to do then it should probably be addressed as a separate issue?


> Furthermore I would call it createAStar... instead of getAStar...

Good point, I will change this.

**Comment by karussell** [comment]
> then it should probably be addressed as a separate issue

You are right!

**Comment by thehereward** [comment]
Methods renamed and commits squashed :-)

**Comment by karussell** [comment]
Thanks!

**Pull request merged**
