### PR TITLE
Path: Allow different visitors for instruction calculation

### PR DESCRIPTION
**Pull request by andreaswolf**
This change allows to use the existing methods with a custom visitor to calculate instructions.

### CODE REVIEW

**Comment by karussell** [comment]
What usage scenario do you have in mind? And also there seems to be a test failing (or is this an uncovered bug?)

**Comment by andreaswolf** [comment]
I need to replace the instruction calculation with my own code and I want to stick als close as possible to upstream Graphhopper (i.e. not mess around with a fork), so I need some extension points.

As for the tests, I actually did not run them (my bad…). I’ll have a look.

**Comment by karussell** [comment]
What do you need to modify for the instruction calculation?

**Comment by andreaswolf** [comment]
Most likely, I will need to completely override it, as I need all road segments in detail (not only tower-tower instructions) and some more information on the segments and the nodes. I did not look into that too deep, but that’s the general concept.

I also don’t know by now if I can reuse the Path class at all or if I need more data in there – but I’m optimistic that the existing data is enough.

**Comment by karussell** [comment]
What I do not understand is if you need to do your own instruction calculation, why not just avoid instruction calculation at all (via hint: instructions=false) and then fetch all edges (calcEdges->gives you all you need) and then do you own instruction calculation?

**Comment by andreaswolf** [comment]
Ah, ok. I think I got the whole thing wrong – just realized that I didn’t even get the refactoring 100% right :-/

Sorry for the hassle, I’ll close this merge request.

**Comment by karussell** [comment]
It is really no problem, often new interaction leads to a better API!

But at the same time we have to make sure that we really need things we add :)

**Comment by andreaswolf** [comment]
I’ll give my best to improve GraphHopper :-)

**Pull request closed without merging**
