### PR TITLE
in GraphHopper class set minOneWayNetworkSize to 200

### PR DESCRIPTION
**Pull request by karussell**
We currently have  
```yml
  prepare.min_network_size: 200
  prepare.min_one_way_network_size: 200
```

in config-example.yml and so we need to make it consistent in the GraphHopper class too. Unfortunately many tests need a change as the do not expect the PrepareRoutingSubnetworks to kick in. To make it a bit convenient I introduced GraphHopper.forTesting, but I'm unsure if we should introduce this there or better create a GraphHopperOSMTest class with this method instead.

### CODE REVIEW

**Comment by easbar** [comment]
I think either way is somehow acceptable, but I think I have a slight preference for not putting the method into `GraphHopper`. `forTesting()` sounds like we are supposed to use it when testing something, but this is not the case (rather the other way around, it should only be used for old tests (or for tests with small graphs where we do not want subnetwork removal). Maybe create a `createHopper(EncodingManager, location, datareaderfile)` (or similar) method in `GraphHopperOSMTest` ? The hopper creation is duplicated quite often in this test, so maybe now is the time to put this into a separate method (and put minnetwork=200 there). And maybe in some other cases we can adjust the test expectations to make the tests work with the default settings ?

**Comment by karussell** [comment]
> I have a slight preference for not putting the method into GraphHopper. forTesting()

Yeah, after thinking over this I agree and will create a new class with just different defaults, to avoid too much friction when creating tests.

> Maybe create a createHopper(EncodingManager, location, datareaderfile) (or similar) method in GraphHopperOSMTest ?

Ah, this is confusing I more meant a new class that just extends GraphHopperOSM and is for Test (GraphHopperOSMForTest :) ?). Will try to find something simple.

> And maybe in some other cases we can adjust the test expectations to make the tests work with the default settings ?

This will be not possible as smaller unit tests will always have too few nodes.

**Comment by michaz** [comment]
Why do you even create a new class? Now it looks like there's something special about subnetwork pruning, and you should always test GraphHopper without it.

Can't you just set the parameter to 0 on the instance, with a config flag, only on the required tests?

**Comment by michaz** [comment]
Or is the problem that all the example networks just completely disappear because they are small? 

Then maybe go all the way and make the change we talked about: Let the "oneWay"-pruner behave like the regular one (not delete the biggest component, ..), and maybe even remove the other one? Or is that too hairy?

**Comment by karussell** [comment]
> Or is the problem that all the example networks just completely disappear because they are small?

Yes.

> Let the "oneWay"-pruner behave like the regular one (not delete the biggest component, ..), and maybe even remove the other one?

Yeah, you are right: keeping the biggest component should be done even it is is smaller than the config.

**Comment by michaz** [comment]
Superseded by 2042.

**Pull request closed without merging**
