### PR TITLE
Enforce non-CH graphs for all LocationIndex implementations

### PR DESCRIPTION
**Pull request by easbar**
These calls to `CHGraph#disconnect` aren't doing anything and there aren't even any shortcut edges involved in this test. This has been like this since a long time, for example already in 2015, e.g. here 7f80425b6a0af9bdfef12c8a873676e39e0a04a6. Maybe we should rename the test or remove it even (is it still testing something useful) ?

### CODE REVIEW

**Comment by karussell** [comment]
Yeah, very old stuff. Was introduced in #30 but at that time we had two different LocationIndex implementations. One for CH and one for none-CH graphs. So probably we do not need this anymore.

**Comment by easbar** [comment]
Ok Ill remove the entire test then

**Comment by easbar** [comment]
Now I am throwing `IllegalState` for all `LocationIndex` implementations and deleted the `LocationIndexCHTest`.

**Comment by karussell** [comment]
Or maybe we remove all other LocationIndex implementations or move them into the tests? I think the only used one is the full edge index for correctness tests.

**Comment by easbar** [comment]
> Or maybe we remove all other LocationIndex implementations or move them into the tests? I think the only used one is the full edge index for correctness tests.

Ok go ahead if you want, for me its sufficient to get rid of the .disconnect calls for now :)

**Pull request merged**
