### PR TITLE
Fixes virtual edge way geometry in case of Position.PILLAR.

### LINKED ISSUE #1552: VirtualEdge includes 'base' node when fetching way geometry.
Is this a bug ? 
https://github.com/graphhopper/graphhopper/commit/b72842df57f1b496032283c07f196c0a956719bb

### PR DESCRIPTION
**Pull request by easbar**
Fixes #1552 .

### CODE REVIEW

**Comment by easbar** [comment]
upside-down ascii chart ?

**Comment by karussell** [comment]
> upside-down ascii chart ?
Sorry, it is not really "a thing". lat increase towards "north" and so this:

```
       1
         \
 0 - * - *
```

Should be this?
```
 0 - * - *
          /
        1
```

**Comment by easbar** [comment]
Ah yes I usually try to follow this convention, too. Here node 1 has lat 0.5 and node 0 hast lat 0 so its fine ? However, I draw the two pillar nodes on a horizontal line even though their latitude was different. Fixed.

**Comment by karussell** [comment]
> Here node 1 has lat 0.5 and node 0 hast lat 0 so its fine ?

Yeah, both not a big issue :D - feel free to merge!

**Comment by easbar** [comment]
Oh snap I forgot to squash :( sorry...

**Comment by easbar** [comment]
Its probably better to merge/squash locally than using button on github ?

**Comment by karussell** [comment]
> Oh snap I forgot to squash :( sorry...

No problem :)

> Its probably better to merge/squash locally than using button on github ?

It will be verified then, but is more effort, so I have no strong opinion and often I use the button (but made the mistake to forget squashing or to do squashing when not wanted already several times ;) )

**Pull request merged**
