### PR TITLE
Android Sample: update to Mapsforge 0.6.1

### PR DESCRIPTION
**Pull request by devemux86**
We released [Mapsforge 0.6.1](https://groups.google.com/forum/#!topic/mapsforge-dev/F_uBzeJ4Thc).

Let's update GraphHopper sample with that.

### CODE REVIEW

**Comment by devemux86** [comment]
We should change also the download link to `0.8` graphs.

Though I don't find them to work, with the error "Encoder foot was used in version 1, but current version is 2".

**Comment by karussell** [comment]
Ups. Thx & will do :)

**Comment by karussell** [comment]
I'm a bit lazy, now we do not need manual editing anymore ;)
https://github.com/graphhopper/graphhopper/commit/dc16f31e53c3aba75e8c011306e83326c7e65651

**Comment by devemux86** [comment]
:+1: 
Any automation is handy for our life as developers!

**Comment by devemux86** [comment]
I updated the PR resolving the conflicts.

**Comment by devemux86** [comment]
Peter shouldn't we put also here an `Android` label for easy reference?

**Pull request merged**
