### PR TITLE
Make it easier to extend Router

### PR DESCRIPTION
**Pull request by boldtrn**
This PR resulted from this discussion: https://discuss.graphhopper.com/t/make-router-extendable/5871

This should make it a lot easier to extend the Router

### CODE REVIEW

**Comment by easbar** [comment]
Hm, github package deployment in master failed with `502 Bad Gateway`. I triggered the job again, lets see...

**Comment by easbar** [comment]
Hm no same problem again :( Will try again tomorrow

**Comment by easbar** [comment]
I tried again but this time I got:

```
Transfer failed for https://maven.pkg.github.com/graphhopper/graphhopper/com/graphhopper/graphhopper-parent/afa3377bf85e1f039b139d07e9995f3f4a61ad74/graphhopper-parent-afa3377bf85e1f039b139d07e9995f3f4a61ad74.pom 409 Conflict
```

:roll_eyes:

**Comment by boldtrn** [comment]
I think this is because the package already exists? https://github.com/graphhopper/graphhopper/packages/245512

It looks like it has been deployed to packages.

**Comment by easbar** [comment]
Ok good then :)

**Pull request merged**
