### PR TITLE
Added missing car4wd icon for web interface button

### PR DESCRIPTION
**Pull request by HarelM**
Described shortly in issue: #2005
Does not fix the issue, only the missing icon...

### CODE REVIEW

**Comment by karussell** [comment]
Thanks for taking care of this issue.

Under which license is the icon? I can see icomoon in the svg code and their license would not allow us the usage.

**Comment by HarelM** [comment]
I drew it, and am using it in [my site](https://israelhiking.osm.org.il/).
I just downloaded the svg from icomoon since this is where I store the font I'm using for the site...

**Comment by karussell** [comment]
Ah, cool. Sorry for my confusion. 

Maybe to highlight the 4-wheel drive we should indicate the 4 wheels like so :) ?

image

Note sure ... probably this violates against some design philosophy as it partially uses 3D :)

[car4wd.zip](https://github.com/graphhopper/graphhopper/files/5315065/car4wd.zip) (had to zip it to upload it here)

**Comment by HarelM** [comment]
Looks good to me :-)

**Comment by HarelM** [comment]
I have updated the icon as can be seen above.
Feel free to merge this.
BTW, is this repository participating in the hacktocberfest event?
I must admit it drove me a bit to send this pull request which was long over due :-)
Cheers.

**Comment by karussell** [comment]
Thanks!

> BTW, is this repository participating in the hacktocberfest event?

No, we do not plan to participate. Still we think how we can make contributing to GraphHopper more attractive while keeping the noise low, e.g. see the [quality problems that digitalocean neglected](https://hacktoberfest.digitalocean.com/hacktoberfest-update).

**Comment by HarelM** [comment]
I have added my repository to participate in the hacktoberfest and haven't received any PR (spam or otherwise :-)).
I think that their latest labeling rules should solve the spam problem. I hope.
I'm getting this PR counted since I submitted it before they changed the rules, but otherwise I would have asked to label it as `hacktobefest-accepted` ;-)
Cheers!
Keep up the good work!

**Pull request merged**
