### PR TITLE
Alternative route for flexibility

### PR DESCRIPTION
**Pull request by karussell**
This pull request finally contains the alternative path refactoring, as well the the alternative routing itself (edge&node based traversal), the necessary UI changes and the old round trip algorithm.

The quality of finding alternatives has increased compared to the old proposal due to the introduction of the 'share' property. Still performance is not optimal.

To enable it just pass `algorithm=alternativeroute` or the Java equivalent. The result looks like:
alt_routes

To calculate more than one alternative use `alternative_route.max_paths=3` (2 alternatives)

This PR makes the PRs #420 & #596 obsolete

TODOs: major speed improvements possible (paper 'Improved Alternative Route Planning'), use bidirectional A*? make alternative search working for CH, post processing of the alternatives to filter away alternatives sharing too much with other alternatives

round trip calculation needs integration tests and a working end path removal or just the addition/replacement via #582

### CODE REVIEW

**Comment by karussell** [comment]
Merged

**Comment by ratrun** [comment]
This feature does not work for me. The icons for the rout alternatives never appear, although I tried a couple of routes. I'm using the latests master.

I'm observing two different kinds of log patterns:

```
2016-01-23 11:40:09,871 [qtp989892772-25] ERROR com.graphhopper.http.GHBaseServlet - point=52.518832%2C13.385704&point=52.516887%2C13.392313&type=json&key=&locale=de-DE&vehicle=bike&weighting=fastest&elevation=false&alternative_route.max_paths=3 127.0.0.1 de_DE Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36 OPR/34.0.2036.50 [52.518832,13.385704, 52.516887,13.392313], took:5.02486E-4, , fastest, bike, errors:[java.lang.IllegalArgumentException: Cannot find point 0: 52.518832,13.385704, java.lang.IllegalArgumentException: Cannot find point 1: 52.516887,13.392313, java.lang.IllegalStateException: No alternative existent]
2016-01-23 11:41:31,269 [qtp989892772-25] INFO  com.graphhopper.http.GHBaseServlet - point=47.834823%2C14.362564&point=47.982568%2C14.659882&point=47.704679%2C14.869995&point=47.813616%2C14.302139&type=json&key=&locale=de-DE&vehicle=bike&weighting=fastest&elevation=false&alternative_route.max_paths=3 127.0.0.1 de_DE Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36 OPR/34.0.2036.50 [47.834823,14.362564, 47.982568,14.659882, 47.704679,14.869995, 47.813616,14.302139], took:0.07062928, , fastest, bike, alternatives: 1, distance0: 198102.09428254317, time0: 774min, points0: 4240, debugInfo: idLookup:0.002169514s; , algoInit:1.01948E-4s, dijkstrabi-routing:0.023992388s, extract time:7.7367E-5;, algoInit:8.9456E-5s, dijkstrabi-routing:0.011493911s, extract time:9.9933E-5;, algoInit:1.69242E-4s, dijkstrabi-routing:0.019175857s, extract time:1.49497E-4;, algoInit:1.01948E-4s, dijkstrabi-routing:0.023992388s, extract time:7.7367E-5;, algoInit:8.9456E-5s, dijkstrabi-routing:0.011493911s, extract time:9.9933E-5;, algoInit:1.69242E-4s, dijkstrabi-routing:0.019175857s, extract time:1.49497E-4, simplify (4825->4240)
```
or 

```
2016-01-23 11:43:54,467 [qtp989892772-27] INFO  com.graphhopper.http.GHBaseServlet - point=47.610792%2C14.773865&point=47.785019%2C14.531479&type=json&key=&locale=de-DE&vehicle=bike&weighting=fastest&elevation=false&alternative_route.max_paths=3&alternative_route.max_paths=3 127.0.0.1 de_DE Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36 OPR/34.0.2036.50 [47.610792,14.773865, 47.785019,14.531479], took:0.006643532, , fastest, bike, alternatives: 1, distance0: 45964.658703533016, time0: 188min, points0: 974, debugInfo: idLookup:0.001119411s; , algoInit:4.5131E-5s, dijkstrabi-routing:0.003284089s, extract time:3.1028E-5;, algoInit:4.5131E-5s, dijkstrabi-routing:0.003284089s, extract time:3.1028E-5, simplify (1070->974)
```

**Comment by stephan75** [comment]
Can that be the same reason why that feature is still not visible on the main instance of https://graphhopper.com/maps/ ?

Or am I blind?

**Comment by karussell** [comment]
> This feature does not work for me

Did you add `algorithm=alternativeroute`?

> Can that be the same reason why that feature is still not visible on the main instance of

It is not deployed and also only usable with flexibility mode not with the used CH. We'll deploy none-CH soonish

**Comment by devemux86** [comment]
FYI I play with it within code and it works as intended.

**Comment by karussell** [comment]
Thanks for confirming @devemux86 

@ratrun let me know when this still not work and we can fix also inconvenient usages etc

Also I'll try to improve performance before releasing but not sure if this will be successful :)

**Comment by ratrun** [comment]
@karussell Thank you. I was missing the second parameter indeed. This looks great.

I mainly looked at the changeset and this page. I didn't find documentation about this feature in the code, only here.
Is it planned to support this feature in the Web UI? It would be great to announce the availablity and display respective UI elements.

**Comment by karussell** [comment]
I'm a bit unsure about this. We can add a checkbox for this but we cannot display this option if CH is queried and also the performance is not yet there where I would like it. We will announce it though in the release notes and pointing to this issue. Then others (and me) can investigate how to implement this in CH and make it faster.

**Comment by devemux86** [comment]
@karussell will you offer 2 possible routes via web interface?

e.g. [BRouter](http://brouter.de/brouter-web/) site uses a combo box for the alternative selection.

Note that the instructions should be updated too with the active route in mind.

Also the alternative selection could be disabled (or emptied) with CH on.

**Comment by karussell** [comment]
This **should** already work :)
See the screenshot with the multiple tabs. if you click one the route is highlighted and the instructions are different.

**Comment by stephan75** [comment]
being not so familiar with parameter finetuning, i tried the following:

adding "?algorithm=alternativeroute" as a postfix to the URL works, but after defining start and end point, a server error is alerted.

adding dev. as a prefix to the URL does not help either.

What about opening a thread about that new feature at https://discuss.graphhopper.com/ ?

**Comment by karussell** [comment]
Yes, let us move the discussion: https://discuss.graphhopper.com/t/alternative-routes/424

**Comment by devemux86** [comment]
@karussell sorry I didn't pay proper attention to the web screenshot, usually playing more with code. :)

**Pull request closed without merging**
