### PR TITLE
Isochrones just by weight (rather than time or distance)

### PR DESCRIPTION
**Pull request by boldtrn**
This PR adds the ability to limit isochrones by weight as well.

Since weight can be any number, I also made the "offset" configurable as well. Probably offset is not the correct word. Maybe search limit? 

Related to #1979 and #1607

### CODE REVIEW

**Comment by michaz** [comment]
Thanks, that makes a lot of sense.

Do you think you could (for now) find a made-up number that works for you and hard-code it there, instead of introducing a new parameter?

These numbers are fudge-factors anyway, _they don't mean anything_, they are just there because they (at some point) fixed something for someone. It'll be replaced by something more clever anyway, soon I hope. ,-)

**Comment by michaz** [comment]
Btw. I would be super-grateful for test-cases which *work* when those numbers are there, and *break* when they don't, i.e. where the isoline is really wrong in a sense, without those numbers. Do you have one with you, by chance? :-)

**Comment by michaz** [comment]
Also, what *is* your use case, if I may ask?

Iso-motorcycle-attractiveness-lines?

**Comment by boldtrn** [comment]
> Do you think you could (for now) find a made-up number that works for your use case (0 perhaps?) and hard-code it there, instead of introducing the new offset parameter?

Yes sure, I could also live with a hardcoded factor of 1.14 for now and completely remove the offset at this point.

To be honest, the main reason I added this was to be compatible with the other two options and to get the same results in the test. So if you remove the `weight_limit_offset` in `IsochroneResourceTest`, the result is not equal anymore.

My goal was to show that the results with the weight limit are equal to the other limits, if you make the input equal, if that's the case that's proof it's working.

> Do you have one with you, by chance? :-)

If you look at the current `IsochroneResourceTest#requestByWeightLimit`, it uses a limit of 3000m, internally we add an offset of 2000m for distance_limit, that's why I added the same offset of the weight_limit as well.

If you compare the results for the distance_limit with and without offset, using this request: `http://localhost:8989/isochrone?point=42.531073,1.573792&profile=car_shortest&type=geojson&distance_limit=3000` (same as the test). The results look like this, red is with offset, green without offset.

Screenshot from 2020-04-23 09-12-52

Now if you compare the actual distance, you see that the one with the offset is closer to the asked 3km.

Screenshot from 2020-04-23 09-13-01
Screenshot from 2020-04-23 09-17-36
Screenshot from 2020-04-23 09-08-16

**Comment by boldtrn** [comment]
Thanks for merging this :tada:

**Pull request merged**
