### PR TITLE
remove legacy turn_costs for isochrone too

### PR DESCRIPTION
**Pull request by karussell**
@easbar is there a reason turn_costs=false/true is not removed for isochrone too?

### CODE REVIEW

**Comment by easbar** [comment]
Not that I know, but its also not used anyway? Ah but the problem is there is an error if its used? I think the argument was that it never has been documented so its not expected to be used? Better ask @michaz and maybe have a look into this dicsussion: https://github.com/graphhopper/graphhopper/issues/1978.

**Comment by easbar** [comment]
But I think this PR is fine, in case its not supposed to be used its also ok to delete it from the hints after profile selection as you do here.

**Comment by easbar** [comment]
Maybe add a test that uses turn_costs and/or edge_based for profile selection, similar to the one that was removed here: 01e56c0e29704cc7bab0da73a88bf5f5b56825f6

**Comment by karussell** [comment]
Thanks! And have added a test.

**Pull request merged**
