### PR TITLE
Enforce allowWrites for GTFS files #2036:

### PR DESCRIPTION
**Pull request by gcheval**
- Attempt to create GTFS storage ONLY if allowWrites == true
- Load GTFS feeds as readOnly if dbFile already exists
- Validate dbFile exists when allowWrites is false

### CODE REVIEW

**Comment by michaz** [comment]
I even think loading a previously imported DB should never require write access.
Should we try to 
- do without the new parameter on loadExisting()
- always load previously-imported DBs in read-only mode
- .. and only check the allowWrites-flag once, namely before trying to import a DB that does not exist? Compare ensureWriteAccess() in GraphHopper.importData

**Comment by michaz** [comment]
(I have a vague memory that this may not work due to something I did for the GtfsRealtime-part. _Maybe_ I modify the DB there, for technical reasons.... :-/)

**Comment by michaz** [comment]
#2036

**Comment by gcheval** [comment]
Hi Michaz,

Applied your comments on the PR. Thanks for your assistance!

- When we find a transit_schedule file, we will attempt to load mapped files and throw a RuntimeException if the files do not reflect the transit_schedule mapping.
- If there's no transit_schedule file, we now validate the write access before attempting to create.

**Comment by gcheval** [comment]
Hey @michaz, What's the remaining actions before getting that PR into a release? Thanks!

**Comment by michaz** [comment]
None. Thank you, will get to this shortly.

**Comment by michaz** [comment]
Merged with db29f6da3bf15d93de933b23dc870ab93f573cda.

https://github.community/t5/GitHub-API-Development-and/Feature-Request-mark-pull-request-as-merged/m-p/40295/highlight/true#M3645

**Pull request closed without merging**
