### PR TITLE
Use android compatible way to unmap a ByteBuffer in java 9

### PR DESCRIPTION
**Pull request by ChristophKaser**
fixes issue #1157

### CODE REVIEW

**Comment by karussell** [comment]
Thanks, much appreciated!

Currently we required signing a CLA via email&scan or signaturit.com 

But I would like to 

 1. improve the visibility who has signed
 2. increase signed & verified commits

So instead of the email&scan procedure: would you instead [sign your commits](https://help.github.com/articles/signing-commits-using-gpg/) and adding you as a contributor list https://github.com/graphhopper/graphhopper/blob/master/CONTRIBUTORS.md with the following line: 

ChristophKaser, agrees to the [project's CLA](https://www.graphhopper.com/individual-contributor-license-agreement/), <some text you like e.g. 'improved Android compatibility'> #1207

**Comment by ChristophKaser** [comment]
Like this?

**Comment by karussell** [comment]
Yes. Wow - this was fast!

I'll just add a link in the description to the CLA before merging.

**Comment by ChristophKaser** [comment]
Sorry, I already did that after writing my comment (I meant to do it before, but forgot to stage my change)

**Comment by karussell** [comment]
No problem and does not matter much, I just included it to avoid repeating the link everytime.

**Pull request merged**
