### PR TITLE
Few more documentation details

### PR DESCRIPTION
**Pull request by henningvs**

### CODE REVIEW

**Comment by henningvs** [comment]
Please wait if you think about merging. I will also comment out the rest in this file.

**Comment by karussell** [comment]
Thanks!

**Comment by karussell** [comment]
Ups, already merged .. would you be so kind to provide this as a new PR :) ?
Also would you mind to ['sign' the CLA](https://www.clahub.com/agreements/graphhopper/graphhopper)? (It doesn't take away your right, just that you agree to the apache license)

**Comment by henningvs** [comment]
Sure, will do this. Also signed the CLA.

**Comment by karussell** [comment]
Thanks!

**Pull request merged**
