### PR TITLE
Enable keeps

### PR DESCRIPTION
**Pull request by boldtrn**
This PR enables keeps, since our clients should reliable enough now.

I currently don't really like the naming "keep left onto ROAD_NAME". I think in this case only on would be better, but this would require a special case for keeps, so I am not sure if this is worth the change, whereas the German translation with `auf` would be fine.

We also need a symbol for the front-end.

### CODE REVIEW

**Comment by devemux86** [comment]
Well until lanes support! :slightly_smiling_face:

**Comment by karussell** [comment]
> This PR enables keeps, since our clients should reliable enough now

We have to postpone this minor change as only recent versions of the clients are reliable enough.

**Comment by boldtrn** [comment]
Ok, sure, no problem :).

**Comment by karussell** [comment]
Ok, we can merge this here now. @boldtrn would you mind update to the latest master? Sorry for the hassle ...

**Comment by boldtrn** [comment]
> Ok, we can merge this here now. @boldtrn would you mind update to the latest master? Sorry for the hassle ...

Done :)

**Comment by karussell** [comment]
I think we also need images for keep :) ! 

https://graphhopper.com/maps/?point=49.464164%2C11.248755&point=49.460203%2C11.245108

**Comment by boldtrn** [comment]
> I think we also need images for keep :) !

Yes I know, but I don't know where the GraphHopper images come from or how to produce them? For [Kurviger](https://kurviger.de/en?point=49.464164%2C11.248755&point=49.460203%2C11.245108) we use [this image](https://kurviger.de/img/mapbox/keep-right.png). I like it and it's CC0. We will also need a u-turn image.

**Comment by devemux86** [comment]
> We will also need a u-turn image.

Note: this would probably need to be without arrow, since the instruction is generic "Make a U-turn".

**Comment by karussell** [comment]
> but I don't know where the GraphHopper images come from or how to produce them

From [here](https://github.com/graphhopper/graphhopper/tree/master/web/src/main/webapp/img) created via inkscape from existing arrows (as svg converted to png)

**Comment by karussell** [comment]
Have added the necessary images

**Comment by karussell** [comment]
Do you have a (quick) example where a U turn is created?

**Comment by boldtrn** [comment]
Any inner city one way primary or secondary should work. Place one waypoint at one side the other at the other side or look at the PathTest example.

**Comment by boldtrn** [comment]
> Do you have a (quick) example where a U turn is created?

Sorry I just briefly commented yesterday from my mobile device. [This](https://graphhopper.com/maps/?point=48.640637%2C9.330654&point=48.640537%2C9.330933) would be one example. Finding them is actually quite easy, as they are usually generated in cities on a bigger primaries or secondaries.

**Pull request merged**
