### PR TITLE
Rename web/com.graphhopper.http to web/com.graphhopper.application

### PR DESCRIPTION
**Pull request by easbar**
For Jigsaw compatibility we must not use the same package across different Maven modules, see #2053. Therefore we cannot use `com.graphhopper.http` in both `web` and `web-bundle` as we currently do. Here I renamed `web/com.graphhopper.http` to `web/com.graphhopper.app` for this reason. *Update* it is now called `web/com.graphhopper.application`.

The only real downside is that now `com.graphhopper.http.GraphHopperApplication` is `com.graphhopper.app.GraphHopperApplication` which means the main class used to start the GH server changed its name and `java` commands using the old name will no longer work. Maybe this is ok, because we just removed the `graphhopper.sh` script and therefore the procedure of starting the server changes between 4.x to 5.0 anyway.

Another alternative would be keeping `web/com.graphhopper.http` as  is and renaming `web-bundle/com.graphhopper.http` instead. I decided against this because it leads to more (downstream) Java code changes and the name `app` seems to be a better fit for the classes in the `web` module (for example it not only has the server but also `ImportCommand`.

### CODE REVIEW

**Comment by boldtrn** [comment]
I personally find `.app` a bit misleading. App often implies some sort of frontend. For me the main purpose of the .http package is to wire the server, so I would propose to go with `com.graphhopper.server`.

**Comment by karussell** [comment]
GraphHopper**App**lication :wink:

**Comment by otbutz** [comment]
> main class used to start the GH server changed its name and `java` commands using the old name will no longer work.

I think most people simply start GH via `java -jar` which retrieves the main class from the jars Manifest. I wouldn't be to concerned about possible breakage here.

**Comment by boldtrn** [comment]
> GraphHopperApplication 😉 (i.e. we already use this "app" naming)

I already thought that you would reply like that :). I still think the naming is not really speaking for itself. 

If you see a package:
`com.example.app`

Would you expect this to contain server code or UI code? I would expect UI code.

**Comment by easbar** [comment]
> I think most people simply start GH via java -jar which retrieves the main class from the jars Manifest. I wouldn't be to concerned about possible breakage here.

Ok, yes, this is true. I already updated the name in the manifest file.

> Would you expect this to contain server code or UI code? I would expect UI code.

Honestly, I would not expect either. I would just see there is some application that I can run. And in fact there **is** a CLI application and a server, so just calling it 'server' would also be misleading to some extent. Then again the maven module is called `web` which causes the same confusion :)

**Comment by otbutz** [comment]
If `web-bundle` is the `GraphHopper Dropwizard Bundle` we could also reflect this in to package naming. eg `com.graphhopper.dropwizard.GraphHopperBundle`

**Comment by easbar** [comment]
> If web-bundle is the GraphHopper Dropwizard Bundle we could also reflect this in package naming. eg com.graphhopper.dropwizard.GraphHopperBundle

It is to some extent related to Dropwizard, but I wouldn't call it like this, because `RouteResource` etc. are close to JAX-RS and in theory can be used with other web frameworks etc.

**Comment by otbutz** [comment]
I wouldn't touch the `resource` package to be honest. But the `com.graphhopper.http` package within `web-bundle` seems to be mostly concerned with dropwizard.

**Comment by easbar** [comment]
Ok, that's true it is just `com.graphhopper.resources` not `com.graphhopper.http.resources` currently.

**Comment by easbar** [comment]
How about `com.graphhopper.application`? That would still be general enough to cover cli+server, it is just a bit longer. And maybe people don't associate this with a frontend/mobile "app" as much as they do when they read 'app'?

**Comment by boldtrn** [comment]
Sounds good, I personally would prefer application over app in this case.

**Comment by easbar** [comment]
Unfortunately this does not work yet. For example MapMatchingResourceTest fails with an NPE (the `gpx` parameter is `null`). Probably we rely on some kind of Dropwizard magic that requires certain things to be in the same package, at least with our current setup.

**Comment by easbar** [comment]
> Probably we rely on some kind of Dropwizard magic that requires certain things to be in the same package, at least with our current setup.

Ah never mind. I just forgot renaming the `src/test/resources/http` folder, and got further confused, because there were two `tour-with-loop2.gpx` files...

**Pull request merged**
