### PR TITLE
Update NameIndex.java

### PR DESCRIPTION
**Pull request by zhiqiangZHAO**
When write it, the address is in byte, not integer.
        names.setHeader(0, BitUtil.LITTLE.getIntLow(bytePointer));
        names.setHeader(4, BitUtil.LITTLE.getIntHigh(bytePointer));

### CODE REVIEW

**Comment by karussell** [comment]
Ouch, thanks! Would you also have failing unit test for this (which is fixed after this change?)

**Comment by zhiqiangZHAO** [comment]
I don't create unit test, since this error is obvious.
I think GH reade the bytePointer again to insert new names.
But actually when the GH loadExisting, it doesn't read new osm data, so, nobody really encouter problem with this.

**Comment by karussell** [comment]
> I don't create unit test, since this error is obvious.

If there is a bug and no test fails we need a unit test to avoid the same bug appearing in the future.

>  I think GH reade the bytePointer again to insert new names.

I see, I'll try to recreate a test showing the problem (or if you would do it is appreciated :))

**Comment by zhiqiangZHAO** [comment]
The test could be, write a nameIndex to disk, then loadExisting, then verify the bytePointer.
:)

**Pull request closed without merging**
