### PR TITLE
Android build target (Eclipse): upgrade to Android 5.1 (API 22)

### PR DESCRIPTION
**Pull request by devemux86**

### CODE REVIEW

**Comment by karussell** [comment]
Okay, maybe we can have #360 before as it looks they do not support 22?

**Comment by devemux86** [comment]
The change is for an Eclipse file (usable locally by the users).

The CI servers use their own repository and as you said they need to support the latest versions.
(e.g. I upgraded today Mapsforge too and we need to update our CI server too)

**Comment by karussell** [comment]
I see, thanks! Do you know how to define that only a subproject is of type 'android' :) ?

**Comment by devemux86** [comment]
Do you mean in CI ?

**Comment by karussell** [comment]
Yes, for travis specific ... I do not see an option that we could use

**Comment by devemux86** [comment]
We use Jenkins CI and Ludwig manages the server.
So I'm afraid I cannot help a lot here.. :(

**Comment by karussell** [comment]
No problem I think I found a solution: https://groups.google.com/forum/#!searchin/travis-ci/android$20/travis-ci/3pzCgvxWZAo/LrSckrasFnkJ

**Pull request merged**
