### PR TITLE
Handling windows line end, fixes #449

### LINKED ISSUE #449: graphhopper.sh windows
hi, i have problems with set up graphhopper on windows. 
i've cloned the git repository but when i want to import the map i get a failure 

$ ./graphhopper.sh import europe_germany_berlin.pbf
./graphhopper.sh: Zeile 2: $'\r': Kommando nicht gefunden.
./graphhopper.sh: Zeile 25: Syntaxfehler beim unerwarteten Wort `$'{\r''
'/graphhopper.sh: Zeile 25: `function printUsage {

do you have ideas what i have to do?

### PR DESCRIPTION
**Pull request by zstadler**

### CODE REVIEW

**Comment by karussell** [comment]
Hmmh, isn't this handled via the '.gitattributes' file already?

```
# Explicitly declare text files we want to always be normalized and converted to native line endings on checkout.
*.sh text
```

**Comment by zstadler** [comment]
On the contrary, the "text" attribute causes the file to be extracted from the git repository with the native line-ending convention of the local OS. This behavior enables, for example, text editing with native editors.

This is exactly the meaning of comment in the paragraph of the '.gitattribute' file quoted above:  the '.sh' files will "_always be normalized and converted to native line endings on checkout_."

On the practical side, I've received this error when I forked the repository a few days ago. Initially I've converted the line endings to Unix-style, but when I found the StackOverflow answer, I've discarded this change, implemented the solution, and verified that the errors are no longer happening.

**Comment by karussell** [comment]
Ok, with which git version did you clone or update your repository? I guess via eclipse (then jgit)?

**Comment by karussell** [comment]
Also do you have a link to the stackoverflow answer?

**Comment by zstadler** [comment]
I'm using the latest GitHub desktop for windows.

The link to the stackoverflow answer is in [my comment on issue 449](graphhopper/graphhopper/issues/449#issuecomment-251070705)

**Comment by karussell** [comment]
Ok, I'll merge then and hopefully this got finally resolved. One tiny thing: would you add 'See #816' to the comment?

**Comment by zstadler** [comment]
There already was a reference to this PR in a [later comment](../issues/449#issuecomment-251071336)

**Comment by karussell** [comment]
> There already was a reference to this PR in a later comment

Sorry, I meant directly in the comment of the script :)

**Comment by karussell** [comment]
Nice - thanks!

**Pull request merged**
