### PR TITLE
Finding the prevEdge from the prevNode

### LINKED ISSUE #1010: Instructions Exception "Couldn't find the edges for..."
We throw an exception when we cannot find the other edges. It happens for some routes that these cannot be found.

We should make the code more robust and maybe just return the calculated sign?

### PR DESCRIPTION
**Pull request by boldtrn**
This issues fixes #1010. The old behavior was created when the algorithm was searching for the current edge and the previous edge. I pass the current edge in the method parameter now, so the current edge is not needed anymore. It makes more sense to search from the previous node to the base node instead of searching from the base node to the previous node in reverse.

I have seen some issues here with VirtualNodes that couldn't be found from the base node correctly. This only happened in combination with a custom weighting and CH, so it is hard to write a test here.

### CODE REVIEW

**Comment by karussell** [comment]
> I have seen some issues here with VirtualNodes that couldn't be found from the base node correctly. This only happened in combination with a custom weighting and CH, so it is hard to write a test here.

Ok, let us fix this other issue first, I think you mean #1013 ?

**Comment by karussell** [comment]
Ok, this has not much to do with #1013. Would you mind to try if you can find this bug in a (integration) test against a CH graph? I can guess this should easily occur if you do

./graphhopper.sh measurement core/files/some.osm.gz

**Comment by karussell** [comment]
Strange, I cannot find such an issue although I thought this could happen frequently due to the graph.disconnect call in PrepareContractionHierarchies

**Comment by karussell** [comment]
I thought I had reproduced the issue but this fix doesn't fix the problem that I had, see [this commit](https://github.com/graphhopper/graphhopper/tree/issue_1014).

See the discussion where [this is coming from](https://discuss.graphhopper.com/t/improving-foot-bike-profile-to-show-instructions-when-turning-if-streetname-doesnt-change/1735/8).

**Comment by karussell** [comment]
The reason that this still fails sometimes for via points is tricky. If we have via points we create 3 virtual nodes e.g. A->B and B->C now if for some reason A is on the path B->C the QueryGraph correctly contains the two virtual edges with A leading to a path like B->...->x1->A->x2->...->C

BUT when using the CH graph the query B->C returns a path with some shortcuts that were extracted but using only real edge like `x1->x2` and not the QueryGraph. Now the turn instruction code relies on finding the previous nodes and fails to find A at node x2.

**Comment by boldtrn** [comment]
Thanks a lot for debugging this and finding a test case @karussell.

I suspected the virtual nodes to be the source of the issue as well. I actually wrote some code to [ignore virtual nodes a couple of weeks ago](https://github.com/boldtrn/graphhopper/commit/aca65dcee5f5129017e2a65b1c8bb81faf13ab16) (I think I mentioned it offline). The code does not fix the issue, that why I haven't created a PR. 

But, I just had an idea. And I have to blame myself for writing unnecessarily complicated code here. I cannot so any reason to not store the prevEdge like we do with prevName. I just implemented this ([see my latest commit to your branch issue_1014](https://github.com/graphhopper/graphhopper/commit/aad04aab303c082f082fc91ab88198111a4f88bd)). Currently I simply force the turn sign if the prevEdge is null (which should not happen frequently, if it happens at all).

WDYT?

**Comment by karussell** [comment]
So this means we can avoid the limitation of the CH path extraction (returning real edges)? Nice!

**Comment by karussell** [comment]
Would you mind to update the PR to the latest HEAD?

**Comment by boldtrn** [comment]
> So this means we can avoid the limitation of the CH path extraction (returning real edges)? Nice!

Yes :). Somehow I must have missed that before...

> Would you mind to update the PR to the latest HEAD?

I just updated the PR to the latest master.

**Pull request merged**
