### PR TITLE
Add Code Of Conduct

### PR DESCRIPTION
**Pull request by ivannieto**

### CODE REVIEW

**Comment by karussell** [comment]
What is your intention with this pull request? Can you explain? We already have a code of conduct ...

**Comment by ivannieto** [comment]
I can't see any file related to any Code of Conduct. Where can I access it?

**Comment by ivannieto** [comment]
My intention is to add this missing file, of course. Willing to create a better community by expanding the Covenant for OSS projects.

http://contributor-covenant.org/

**Comment by karussell** [comment]
Please read https://github.com/graphhopper/graphhopper/blob/master/.github/CONTRIBUTING.md

**Comment by ivannieto** [comment]
Oh, missed that @karussell sorry. 😄

**Pull request closed without merging**
