### PR TITLE
Add JSON dependency to core

### PR DESCRIPTION
**Pull request by karussell**
As discussed [here](https://discuss.graphhopper.com/t/json-jackson-dependency-in-gh-core/2807) introducing the JSON dependency in core could make several things less clunky, especially since it seems we need this in #1112 in the core as we use the json format instead of the hacky binary+text mix of StorableProperties. (It will not happen for 0.10)

### CODE REVIEW

**Comment by karussell** [comment]
If JTS is able to [read and write geojson on its own](https://github.com/graphhopper/graphhopper/issues/1297) we probably don't need to add jackson to the core.

**Comment by willcohen** [comment]
I should note that JTS also broke itself into a few modules, so [jts-core](https://search.maven.org/#artifactdetails%7Corg.locationtech.jts%7Cjts-core%7C1.15.0%7Cbundle) is the main replacement, and then there's also [jts-io-common](https://search.maven.org/#artifactdetails%7Corg.locationtech.jts.io%7Cjts-io-common%7C1.15.0%7Cjar).

**Comment by karussell** [comment]
Thanks for highlighting this! I think we will then better stay with jackson instead of using the inactive json-simple. (https://github.com/conveyal/gtfs-lib/issues/97#issuecomment-370471610)

**Comment by karussell** [comment]
Really hard decision, but I think for now we close this and try to keep JSON out of the core. Still unsure.

**Pull request closed without merging**
