### PR TITLE
Move importOrLoad outside of Guice and use addShutdownHook

### PR DESCRIPTION
**Pull request by karussell**
Furthermore I made the createGraphHopper method protected to being able using the same instance with SpatialRuleLookupBuilder

### CODE REVIEW

**Comment by michaz** [comment]
I really wouldn't recommend extending ``DefaultModule``, or designing it to be extended.

I like the ShutdownHook, but did you test this? I faintly remember that getProvider() doesn't work _after_ provisioning, so it would only work the way it is in my code (being called and remembered at configuration time). But I'm not sure.

Using ShutdownHooks should probably mean we should remove the Servlet deployment option by deleting ``GuiceServletConfig``.

**Comment by karussell** [comment]
> I really wouldn't recommend extending DefaultModule, or designing it to be extended.

Ok, then I'll create a static helper or something so that one can reuse the SpatialLookup init code.

> I like the ShutdownHook, but did you test this?

No, will call this earlier then. Should we create an (integration) test for this? 

> Using ShutdownHooks should probably mean we should remove the Servlet deployment option by deleting GuiceServletConfig.

Ah, now I understand the difference. Then I'll keep your idea with the filter for now.

**Comment by michaz** [comment]
> GuiceServletConfig

Speaking of this: This probably doesn't currently work anyway. GHServer and GuiceServletConfig create their modules differently -- they shouldn't, they should create exactly the same Module. Otherwise, we need all tests for both of them separately. ,-)

Or we should delete it.

**Comment by michaz** [comment]
The most principled way would probably if ``GHServer`` would use ``GuiceServletConfig`` to create its stuff, and not use its own way to create an injector.

**Comment by karussell** [comment]
The war:war deployment makes problems anyway #297, maybe we should just drop support for it and remove GuiceServletConfig

**Comment by karussell** [comment]
Making the tests identical was easy via `setUpGuice(server.createModule());` in BaseServletTester

**Comment by michaz** [comment]
> Also this probably means that GHServer isn't really testable (as a Java class) anymore. It leaks resources which are only closed when the JVM quits. Whereas previously, jetty would close everything on stop().

Hmm, we have to remember this now: server.stop() does not close the resources now. With the filter version, it would have. Isn't there a jetty feature like a stop()-hook where we can close, instead of a Runtime-shutdown-hook?

**Comment by karussell** [comment]
> Isn't there a jetty feature like a stop()-hook where we can close, instead of a Runtime-shutdown-hook?

No idea, but our GHServer has a stop method which we should probably better call?

**Comment by karussell** [comment]
Also as this was already merged by me you would have to create a new PR unfortunately...

**Comment by michaz** [comment]
Yes I know. I just wanted to re-emphasize what this means.

- Jetty stops itself on JVM shutdown
- now we also close resources on JVM shutdown
- GHServer.stop results in Jetty.stop
- but Jetty.stop does not result in closing resources.

**Comment by michaz** [comment]
Ok, I'll look for a jetty-stop-listener or something, then we can close the resources there and don't need our own shutdown hook.

**Pull request merged**
