### PR TITLE
Refine OSMGetOffBikeParser

### PR DESCRIPTION
**Pull request by OlafFlebbeBosch**
* No need to get off bike on paths
  * Adding bicycle/official and bicycle/permissive for riding

Please read [our contributing guide](https://github.com/graphhopper/graphhopper/blob/master/CONTRIBUTING.md) and note that also your contribution falls under the Apache License 2.0 as outlined there.

Your first contribution should include a change where you add yourself to the CONTRIBUTORS.md file.

### CODE REVIEW

**Comment by karussell** [comment]
Thanks @OlafFlebbeBosch this looks good! This would need a review from @ratrun :) as I'm unsure why we had getting of the bike for paths.

**Comment by boldtrn** [comment]
> I'm unsure why we had getting of the bike for paths

I always thought that the idea was that most paths are narrow and might require to get off the bike if you are an insecure rider or if there is traffic coming the opposite way - a bit like "you might have to get off the bike".

I would be in favour of removing path here :)

**Comment by karussell** [comment]
Yes, although the wiki even explicitly states: "highway=path | A generic multi-use path open to non-motorized vehicles, implicitly allowed for pedestrians, cyclists, …"

if a path has foot=designated and no bicycle tags we should still mark get_off_bike as true.

**Comment by boldtrn** [comment]
> if a path has foot=designated and no bicycle tags we should still mark get_off_bike as true (i.e. the default access is a bit tricky for path?)

Yes, probably you are right, as this would be identical to a `highway=footway` with no bicycles tags?

**Comment by OlafFlebbeBosch** [comment]
@boldtrn @karussell : As I understand the code already works the way you are proposing ? Should I add explicit tests for the scenarios at hand ?

**Comment by ratrun** [comment]
I didn't know that the default accessibility for `highway=path` implicitly allows bicycles. Here in Austria most small ways in the forest are tagged like this, but accesss for bikes is usually forbidden unlike it is explicitely allowed. So this was a localisation issue - see https://wiki.openstreetmap.org/wiki/OSM_tags_for_routing/Access_restrictions#Austria.

**Comment by karussell** [comment]
> I didn't know that the default accessibility for highway=path implicitly allows bicycles

Ah, ok. So this PR is fine for you?

> Should I add explicit tests for the scenarios at hand ?

Yes, if I understand it correctly, it would be good to have something like this:

```
way = new ReaderWay(1);
way.setTag("highway", "path");
assertFalse(isGetOffBike(way));

way.setTag("footway", "yes");
assertTrue(isGetOffBike(way));
```

**Comment by otbutz** [comment]
Sounds like this would be a better fit for CountryRules to be honest.

**Comment by OlafFlebbeBosch** [comment]
Thanks @ratrun  for the insights into Austria specific rules. I wasn't aware of these!

I will update to reinstantiate the "path" in the get off bike sections again and will see into looking the proposal of @otbutz in an follow-up PR.

**Comment by OlafFlebbeBosch** [comment]
Revoked the change to "path" for now. Adding a bit more tests. Hope it was ok to squash the changes

**Comment by ratrun** [comment]
@OlafFlebbeBosch 
Thanks for changing the code for `path` again. I believe that the correct global default is implemented and therefore I'm fine with this PR now. 
@karussell Thanks for asking!

**Comment by karussell** [comment]
> I believe that the correct global default is implemented 

How do you think should it behave without bicycle tags?

I do not think this works in this PR:

```
way.setTag("highway", "path");
way.setTag("footway", "yes");
assertTrue(isGetOffBike(way));
```

**Comment by boldtrn** [comment]
> way.setTag("footway", "yes");

Do you mean `foot=designated` or `highway=footway`?

**Comment by karussell** [comment]
Ah, yes "foot=designated" is probably what I meant - and if this works already then I'm fine :)

**Comment by OlafFlebbeBosch** [comment]
Hi,  I am adding @karussell proposed test explicitly.
Sorry something went wrong while pushing the previous update. The change should be in merge-able state now.

**Comment by karussell** [comment]
Thanks @OlafFlebbeBosch !

**Pull request merged**
