### PR TITLE
Move mx beans2 measurement

### PR DESCRIPTION
**Pull request by oflebbe**
Last one for now :)

Move two problematic functions for porting to iOS to the separate tool where it is used, only.

### CODE REVIEW

**Comment by easbar** [comment]
Ok, this makes #2062 obsolete then?

**Comment by oflebbe** [comment]
Not exactly. It builds up on top of #2062. Since it will git conflicts if I would place independent PR. 
Was testing if #2062 has a chance to get accepted first .

**Comment by easbar** [comment]
> Not exactly. It builds up on top of #2062. Since it will git conflicts if I would place independent PR.
Was testing if #2062 has a chance to get accepted first .

Oh ok but this would only work if there were no other commits anyway, because we are usually squashing all PRs into a single commit to keep a linear history.

**Comment by easbar** [comment]
Thanks!

**Pull request merged**
