### PR TITLE
Fix GraphHopperWeb to pass alternative_route hints to the server

### PR DESCRIPTION
**Pull request by elibar**
Passing all hints that starts with alternative_route as quay parameters on the route request

### CODE REVIEW

**Comment by karussell** [comment]
Are the FootFlagEncoders intended to be included here?

We should not filter the hints (i.e. remove the `if(key.startsWith("alternative_route.")){`) and calling URLEncode on the value and key is very important here.

**Comment by elibar** [comment]
Hi 
The FootFlagEncoders changes are not intended to be included in this pull request. Though  I think we should change the foot weights. I stopped using the avoidHighwayTags weights as I got bad feedback from pedestrians about the generated routes.

If removing the `if(key.startsWith("alternative_route.")` we should remove also the code that deals with the key, so we will not have the key query parameter twice in the request

**Comment by karussell** [comment]
> Maybe this is a little bit off topic here

@ratrun Thanks for this JS catch. Would you mind to open up a new issue for this? Also the `.` is intended to work in JS like it supposed to be: would you mind to try: `{...., "alternative_route": { "max_paths" : 3 } }` instead?

> If removing the if(key.startsWith("alternative_route.") we should remove also the code 
> that deals with the key, so we will not have the key query parameter twice in the request 

@elibar what do you mean here? I would like to avoid changing code here again, if there are new parameters (e.g. besides alternative_route) necessary to add.

**Comment by elibar** [comment]
There is a special handle for the "key" parameter
` String tmpKey = request.getHints().get("key", key);` 
and 
` if (!tmpKey.isEmpty())`
`                url += "&key=" + tmpKey;`

If we have code that copy all hints to query parameters the "key" parameter will be added twice to the URL, once by the above code and once by the code that handle all hints.

**Comment by karussell** [comment]
> There is a special handle for the "key" parameter

Ah, yes, indeed, also: 'instructions' and 'elevation'

A bit tricky is `calcPoints` which would be the only param which we should just ignored in the hints loop.

**Comment by ratrun** [comment]
>Would you mind to open up a new issue for this? Also the . is intended to work in JS like it supposed to be: would you mind to try: {...., "alternative_route": { "max_paths" : 3 } } instead?

Thank you. Shortly after having sent this comment, I had the same idea. But this required a couple of ofther changes as well. See d4c9c7400210ee6a033ef52f36e1583c33af1fe4 . The good thing is that URI parameter renaming and a new issue is not necessary.

**Comment by karussell** [comment]
> But this required a couple of ofther changes as well.

What do you mean here? It looks like you did not base the change on the most recent master (?)

**Comment by ratrun** [comment]
@karussell: Somehow your response does not appear here. I received the following via the mail notification only.

>>    But this required a couple of other changes as well.

>What do you mean here? It looks like you did not base the change on the most recent master (?)

Yes, the change is based on my master, not the official one. The reason was the following statement in #640 about the alternative_route WEB UI support:

>I'm a bit unsure about this. We can add a checkbox for this but we cannot display this option if a CH-based query is running yet and also the performance is not yet there where I would like it. We will announce it though in the release notes and pointing to this issue. Then others (and me) can investigate how to implement this in CH and make it faster for one of the releases afterwards.

Despite that I wanted to point to a working implementation. It might help others, because it took me a couple of attempts to get it working.

**Comment by karussell** [comment]
> @karussell: Somehow your response does not appear here. I received the following via the mail notification only.

Sorry, I removed it as I saw you updated the change and it pointed before to a the big commit :) and now it is clear.

> Despite that I wanted to point to a working implementation. It might help others, because it took me a couple of attempts to get it working.

Probably not a bad idea. Still I like to have the UI clean, maybe show these (and later) advanced options only when clicking on a small gear wheel icon or something?

**Comment by ratrun** [comment]
>Still I like to have the UI clean, maybe show these (and later) advanced options only when clicking on a small gear wheel icon or something?

The UI remains unchanged for the end-user in case that a CH server instance is used in the backend. For CH backend instances the sliders, which do not make sense otherwise, are hidden.

**Comment by karussell** [comment]
> The UI remains unchanged for the end-user in case that a CH server instance is used 
> in the backend. For CH backend instances the sliders, which do not make sense otherwise, are hidden.

Sure, but even for flexibility mode I would avoid it. That won't be the only option to come ...

**Comment by ratrun** [comment]
>Sure, but even for flexibility mode I would avoid it. That won't be the only option to come ...

Yes. But I think that the web UI source code should always support all the features the core server source code provides. Otherwise it gets difficult for contributors, as we would always need to look up documentation or code for the available parameters and add them to the URL by hand. This is not convenient at all.

Do I understood it right that you intend to be able to announce from a server side configuration setting which GUI elements to show on the web UI? In this case, this probably should be added as part of the flexibility enhancements right from the start. Another more complicated solution is to dynamically create the web UI using npm based via build settings. But I would like avoid that as this sounds too complicated.

**Comment by karussell** [comment]
> This is not convenient at all.

I understand what you mean but keep in mind that there are already many features not accessible from the UI. This is partly from the fact that is does not make much sense and partly from the lack of time to do this properly like it was the case for alternative routes. And just adding more controls won't make the UI easier for beginners.

> Do I understood it right that you intend to be able to announce from a server side configuration

I didn't mean that here.

> But I would like avoid that as this sounds too complicated.

This is already done with e.g. the elevation support and is not really complex (or maybe I misunderstand what you meant?)

**Comment by karussell** [comment]
I've fixed this - @elibar let me know if this works for you this way.

**Comment by karussell** [comment]
@ratrun for now I make several features more visible via the new ['overview'](https://github.com/graphhopper/graphhopper/blob/master/README.md#overview) in the readme - let me know if something is missing or needs explanation. Please create a separate issue for the UI change.

**Pull request closed without merging**
