### PR TITLE
Add an optional configuration setting for routing through barriers

### PR DESCRIPTION
**Pull request by zstadler**
An interim solution for issue  graphhopper/graphhopper#754

### CODE REVIEW

**Comment by karussell** [comment]
Thanks. This is somehow mixed with a new car4wd profile? Sounds interesting but should be put in another PR.

**Comment by zstadler** [comment]
It was not my intention to mix the two topics. 

I was not aware that if I continue development on the master branch of the forked repository, after submitting the pull request, will cause a change in the contents of the pull request.

What would be the best practice to recover form this unintended mix-up?

**Comment by karussell** [comment]
We can close here and you can create one branch for every new feature that you intend to merge (Then you can easily create one PR per feature branch). And then in your master you merge all the features.

**Comment by zstadler** [comment]
OK. Dropping this PR.
Opened PR #817 instead

**Pull request closed without merging**
