### PR TITLE
Exception Mapping

### PR DESCRIPTION
**Pull request by michaz**
Based on #1389, moved the creation of exception responses to where it belongs (in Dropwizard's opinion): To an exception mapper and a message body writer, and a regular JSON serializer for the JSON case. _Those_ can easily be shared by other Repos (map-matching, matrix).

Dropwizard/Jersey want the switch for content types to be _mainly_ done based on the header, not on a query param, but other things are also possible: "re-mapping" or "normalizing" those things in a Filter is what's recommended. (Jersey has an example where the same is done for filename extensions. That's where I copied this from.)

The explanation how it works is in ``GraphHopperBundle``, where it's plugged together:

```
        // If the "?format=gpx" parameter is present, sets a corresponding media type header
        environment.jersey().register(new FormatGPXFilter());

        // Together, these two take care that MultiExceptions thrown from RouteResource
        // come out as JSON or GPX, depending on the media type
        environment.jersey().register(new MultiExceptionMapper());
        environment.jersey().register(new MultiExceptionGPXMessageBodyWriter());
```

### CODE REVIEW

**Comment by michaz** [comment]
..and the only thing which complicates doing the same thing for the regular case (the successful response) is that they are parameterized (by "do we want instructions?" and such). Not sure how that is supposed to be done yet.

**Comment by michaz** [comment]
If we like this, we can codify in the same way the GraphHopper-convention (correct me if I'm wrong) that IllegalArgumentExceptions should correspond to status 4xx. Then we don't have to wrap them in WebApplicationExceptions (as before) or MultiExceptions (as now) but can throw them directly, even from the library (if it's only one).

**Comment by Nakaner** [comment]
I lack the in-depth knowledge of Dropwizard etc. to review the code but I checked out your branch and tested it.

Is it intended that the `type` parameter of the query string is ignored and only the HTTP `Accept` header field (defaults to JSON) matters? Valid requests would return GPX data if `type=gpx` is represent but no `Accept` header field.

`curl  -H "Accept: application/gpx+xml" "localhost:8989/route?point=40.0,30.0&point=20.0,30.0&vehicle=car&format=gpx"` results in an XML error response but if I omit the HTTP `Accept` header field, JSON is returned.

The HTTP API documentation don't mention at all that you need to send a header.

**Comment by michaz** [comment]
> Is it intended that the type parameter of the query string is ignored

Err.. no. Hold on..

**Comment by michaz** [comment]
Ahh, look, it's supposed to be `&type=gpx`, not `&format=gpx`. Then it works.

Were you primed by my class name ``FormatGPXFilter`` maybe? No idea why I called it that, will change.

**Comment by karussell** [comment]
> IllegalArgumentExceptions should correspond to status 400

:+1:

**Pull request merged**
