### PR TITLE
CustomModelParser can handle multiple areas

### PR DESCRIPTION
**Pull request by GProbo**
Solving issue #2240 
CustomModelParser used to create a Java file with a JsonFeature called feature. In case of multiple areas the JsonFeature was created twice.

The following is the code created by CustomModelParser.
  @Override
   public void init(EncodedValueLookup lookup, com.graphhopper.routing.ev.DecimalEncodedValue avgSpeedEnc, Map<String, com.graphhopper.util.JsonFeature> areas) {
this.avg_speed_enc = avgSpeedEnc;
JsonFeature feature = (JsonFeature) areas.get("milano");
this.in_area_milano = new Polygon(new PreparedGeometryFactory().create(feature.getGeometry()));
JsonFeature feature = (JsonFeature) areas.get("modena");
this.in_area_modena = new Polygon(new PreparedGeometryFactory().create(feature.getGeometry()));
if (lookup.hasEncodedValue("road_class")) this.road_class_enc = (EnumEncodedValue) lookup.getEncodedValue("road_class", EncodedValue.class);
   }

I added in CustomModelParser.createClassTemplate an id to the JsonFeature feature.
Now CustomModelParser create the following code:
 @Override
   public void init(EncodedValueLookup lookup, com.graphhopper.routing.ev.DecimalEncodedValue avgSpeedEnc, Map<String, com.graphhopper.util.JsonFeature> areas) {
this.avg_speed_enc = avgSpeedEnc;
JsonFeature feature_milano = (JsonFeature) areas.get("milano");
this.in_area_milano = new Polygon(new PreparedGeometryFactory().create(feature_milano.getGeometry()));
JsonFeature feature_modena = (JsonFeature) areas.get("modena");
this.in_area_modena = new Polygon(new PreparedGeometryFactory().create(feature_modena.getGeometry()));
if (lookup.hasEncodedValue("road_class")) this.road_class_enc = (EnumEncodedValue) lookup.getEncodedValue("road_class", EncodedValue.class);
   }

### CODE REVIEW

**Comment by karussell** [comment]
Thanks a lot for this!

Can you add yourself also to the [contributing doc](https://github.com/graphhopper/graphhopper/blob/master/CONTRIBUTORS.md)?

**Comment by GProbo** [comment]
> Thanks a lot for this!
> 
> Can you add yourself also to the [contributing doc](https://github.com/graphhopper/graphhopper/blob/master/CONTRIBUTORS.md)?

Done!

**Comment by karussell** [comment]
Thanks! And sorry that I did not mention it but the list is sorted :) ... can you move it to the correct place? (this way a human lookup is faster ;) )

**Comment by GProbo** [comment]
Sorry! My bad!

**Comment by karussell** [comment]
Thanks a lot! Also for finding this and playing around with this new feature :)

**Pull request merged**
