### PR TITLE
Add handling of conditional turn restrictions

### PR DESCRIPTION
**Pull request by easbar**
Unfortunately #1683 does not work yet, because there can be cases with multiple conditional turn restrictions like so:

```
restriction:bus=...
restriction:hgv=...
```

Therefore I reverted the previously merged #1683 and reopened here.

See #1735

### CODE REVIEW

**Comment by easbar** [comment]
@sguill Do you know how to address this problem ?

**Comment by sguill** [comment]
Yes, my first idea was to return silently the first match, if you remember. But, now I think, it is better to return a list. Do you agree ?

**Comment by easbar** [comment]
> Yes, my first idea was to return silently the first match, if you remember.

Yeah, but this way we would simply ignore some restrictions (and arbitrarily pick some of them) which I think is worse. 

> But, now I think, it is better to return a list. Do you agree ?

Yes apparently a relation with restriction must yield a list of multiple restrictions. However, if possible I would still try to feed information about single restrictions to the encoder ? So take the OSM relation, build a list of things that each represent a specific restriction (e.g. left only for buses) and then feed them one by one into `encoder.acceptTurnRelation`, does that make sense ?

I also thought about how the `except` list should be interpreted when there are multiple conditional restrictions and came to the conclusion that all these exceptions should be applied to *all* the restrictions within the relation (?).

**Comment by sguill** [comment]
I made the changes in commit 15ba63f *multiple conditional turn restriction types* in branch *accept_turn_relation* but it is not taken into account. I don't know how to do?

**Comment by easbar** [comment]
> but it is not taken into account.

Ah yes this is because you pushed to `sguill/accept_turn_relation`, but this PR uses `graphhopper/accept_turn_relation`. I probably should have created a PR using `sguill/accept_turn_relation`, because you will not be able to push to `graphhopper/accept_turn_relation` directly.

Now I think you need to checkout `graphhopper/accept_turn_relation` locally, make your recent changes, push it to your fork (under some new name) and create a new PR. You could also just create a new PR using `sguill/accept_turn_relation`, but then you need to make sure that everything is still included. I think right now it is missing most of your changes (compared to `graphhopper/accept_turn_relation`), they got lost because you merged master that included the revert commit (I already took care of this in `graphhopper/accept_turn_relation`).

**Comment by easbar** [comment]
Closing in favor of #1738

**Pull request closed without merging**
