### PR TITLE
switch to org.locationtech.jts

### PR DESCRIPTION
**Pull request by ChristophKaser**
I changed the dependency on com.vividsolutions.jts to org.locationtech.jts, because it does not use the LGPL, which makes it easier to deploy on android devices (it is really hard to use LGPL-libraries correctly in android due to the way all libraries are combined in the APK)

### CODE REVIEW

**Comment by ChristophKaser** [comment]
Sorry, I forgot I had removed some modules in my build that had test failures with the new library. I will try to fix those failures and open a new pull request.

**Comment by ChristophKaser** [comment]
Unfortunately for now, it is not possible to upgrade reader-json, because it has a dependency on bedatadriven/jackson-datatype-jts, which still uses the old com.vividsolutions.jts-library. It think it is necessary to fork jackson-datatype-jts (or directly include the necessary code in reader-json), or wait for the maintainer of jackson-datatype-jts.

**Comment by karussell** [comment]
Cool, this was fast - thanks a bunch! And really cool that you already pinged the jackson-datatype-jts maintainer here: https://github.com/bedatadriven/jackson-datatype-jts/issues/17 :) !

**Comment by karussell** [comment]
BTW: If the maintainer does not respond this year or so then we'll fork :). Probably then the best would be to have it in this repo, hmmh.

**Comment by karussell** [comment]
It looks like we have to fork it ... https://github.com/graphhopper/jackson-datatype-jts ... but when I try to change to the new dependency I get:
```
Could not resolve dependencies for project com.bedatadriven:jackson-datatype-jts:jar:2.5-SNAPSHOT: Could not find artifact org.locationtech.jts:jts:jar:1.15.0 in central (https://repo.maven.apache.org/maven2)
```
even with `mvn clean install -U` and despite [maven central](https://search.maven.org/#artifactdetails%7Corg.locationtech.jts%7Cjts%7C1.15.0%7Cpom) should have it!? What am I doing wrong :) ?

**Comment by karussell** [comment]
Ups, it is jts-core, see https://dev.locationtech.org/mhonarc/lists/jts-dev/msg00214.html

**Comment by karussell** [comment]
Have published a new release under com.graphhopper:jackson-datatype-jts:jar:0.10-2.5 see:

https://github.com/graphhopper/jackson-datatype-jts/releases/tag/0.10-2.5

Will be available on maven in the next hour probably.

**Comment by karussell** [comment]
Something went wrong. Released it again as com.graphhopper.external:jackson-datatype-jts:jar:0.10-2.5-1

https://github.com/graphhopper/jackson-datatype-jts/releases/tag/0.10-2.5-1

**Pull request closed without merging**
