### PR TITLE
Update russian translation

### PR DESCRIPTION
**Pull request by drnextgis**

### CODE REVIEW

**Comment by devemux86** [comment]
I think for translations you need to use the [speadsheet](https://github.com/graphhopper/graphhopper/blob/master/docs/core/translations.md) and then Peter merges the changes.

**Comment by drnextgis** [comment]
We've used this spreadsheet and I've made PR accordingly [this](https://github.com/graphhopper/graphhopper/blob/master/docs/core/translations.md) doc.

**Comment by karussell** [comment]
Oh, nice. Thanks for taking the time to provide this as a PR!

**Comment by karussell** [comment]
BTW: would you mind to 'sign' the [contributor license](https://www.clahub.com/agreements/graphhopper/graphhopper)? To (additionally) confirm that we can release your work under the Apache License.

**Comment by drnextgis** [comment]
Of course.

**Comment by karussell** [comment]
Thanks!

**Comment by drnextgis** [comment]
I've updated code from this repository and rebuilt my WAR-file, but new translation does not show up.

**Comment by karussell** [comment]
You have to rebuild the core jar too: `cd core; mvn -DskipTests=true clean install`

Or instead of this lengthy process you setup your IDE (like netbeans or intelliJ) which will auto-compile on save

**Comment by drnextgis** [comment]
Thank! It works.

**Pull request merged**
