### PR TITLE
Use ForkJoinPool for concurrent processing

### PR DESCRIPTION
**Pull request by otbutz**
see https://github.com/graphhopper/graphhopper/pull/2828#issuecomment-1566139538

### CODE REVIEW

**Comment by otbutz** [comment]
@easbar what do you think?

**Comment by easbar** [comment]
I like it because the code is simple and in my (limited) tests it even seemed to be a bit faster. Can you update this to recent master, please?

**Comment by otbutz** [comment]
Done :)

**Comment by easbar** [comment]
Thanks

**Pull request merged**
